- dotnet/CoreLib/CoreLib.csproj
- dotnet/CoreLib/Pipeline/Queue/AzureQueue.cs
- dotnet/CoreLib/Pipeline/Queue/FileBasedQueue.cs
Choose net6.0 for ease of integration.
Aligns with SK and other version decision points
> Use dotnet 6.0

- dotnet/CoreLib/Pipeline/Queue/AzureQueues/DependencyInjection.cs
- dotnet/CoreLib/Pipeline/Queue/FileBasedQueues/FileBasedQueue.cs
- dotnet/CoreLib/Pipeline/Queue/FileBasedQueues/FileBasedQueueConfig.cs
- dotnet/CoreLib/Pipeline/Queue/RabbitMq/DependencyInjection.cs
- dotnet/Service/appsettings.json
> File based queue created dir by default

- dotnet/nuget/nuget-package.props
> Change icon and readme paths to absolute in common props paths

- .github/workflows/publish.yaml
- dotnet/Service/Service.csproj
- samples/001-dotnet-Serverless/001-dotnet-Serverless.csproj
- samples/002-dotnet-WebClient/002-dotnet-WebClient.csproj
- samples/004-dotnet-ServerlessCustomPipeline/004-dotnet-ServerlessCustomPipeline.csproj
- samples/005-dotnet-ExtractTextFromDocs/005-dotnet-ExtractTextFromDocs.csproj
- samples/006-dotnet-CustomHandler/006-dotnet-CustomHandler.csproj
- samples/007-using-azure-cognitive-search/007-using-azure-cognitive-search.csproj
> Samples target framework to dotnet 6.0

- .github/workflows/publish.yaml
> Set publish workflow dotnet version to 7

- .github/workflows/publish.yaml
Find the correct packages to push to avoid pushing duplicates.
> Update regex for dotnet nuget push to push the correct packages

- samples/008-dotnet-nl2sql/nl2sql.console/Repo.cs
Minor update to point to correct folder
> fix reference to sample folder

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
- dotnet/CoreLib/Pipeline/BaseOrchestrator.cs
- examples/006-dotnet-CustomHandlerAsAService/Program.cs
Remove from memory builder dependency on `Microsoft.AspNetCore.Builder`, e.g. `WebApplicationBuilder`
> Refactoring memory builder

- dotnet/ClientLib/ISemanticMemoryClient.cs
- dotnet/ClientLib/MemoryWebClient.cs
- dotnet/ClientLib/Models/SearchQuery.cs
- dotnet/CoreLib/Memory.cs
- dotnet/CoreLib/MemoryService.cs
- dotnet/CoreLib/Search/SearchClient.cs
- dotnet/CoreLib/WebService/HttpDocumentUploadRequest.cs
- dotnet/Service/Program.cs
- dotnet/nuget/nuget-package.props
- tools/search.sh
* Add new "limit" param to search API
* Fix "steps" param not propagating in HTTP scenarios
* Add cancellation token to web API endpoints
* Bump to version 0.2
> Allow to limit search results

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
Add simple vector Db to service when it's selected.
> Add simple vector DB to service

- dotnet/CoreLib/MemoryStorage/DevTools/ISimpleStorage.cs
- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDbConfig.cs
- dotnet/Service/appsettings.json
- examples/004-dotnet-ServerlessCustomPipeline/appsettings.json
- examples/005-dotnet-InProcessMemoryWithCustomHandler/appsettings.json
- examples/006-dotnet-CustomHandlerAsAService/appsettings.json
- tests/FunctionalTests/appsettings.json
Add volatile memory storage to support a more complete local story for chat copilot.
This PR follows the suggestion in this comment: https://github.com/microsoft/semantic-memory/pull/30#issuecomment-1694797319
> Add volatile memory storage

- examples/200-dotnet-nl2sql/Nl2Sql.sln
- examples/200-dotnet-nl2sql/README.md
- examples/200-dotnet-nl2sql/nl2sql.config/README.md
- examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/generatequery/skprompt.txt
- examples/200-dotnet-nl2sql/nl2sql.config/schema/README.md
- examples/200-dotnet-nl2sql/nl2sql.console/appsettings.json
- examples/200-dotnet-nl2sql/nl2sql.harness/Nl2Sql.Harness.csproj
- examples/200-dotnet-nl2sql/nl2sql.harness/SqlSchemaProviderHarness.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Internal/SKContextExtensions.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/SqlQueryGenerator.cs
Updates based on learning from partner feedback:
- Clarify need for embedding configuration
- Clarify model naming details (Azure vs Open AI)
- Clarify reverse-engineering process
- Fix solution file
- Fix relevancy threshold
- Fix broken readme links (case)
- Update generate prompt example to match current (no: * all columns)
> Bug fixes, package updates, and readme enhancements

- dotnet/ClientLib/ClientLib.csproj
- dotnet/CoreLib/CoreLib.csproj
- dotnet/InteractiveSetup/InteractiveSetup.csproj
- dotnet/Service/Service.csproj
- examples/001-dotnet-Serverless/001-dotnet-Serverless.csproj
- examples/002-dotnet-WebClient/002-dotnet-WebClient.csproj
- examples/004-dotnet-ServerlessCustomPipeline/004-dotnet-ServerlessCustomPipeline.csproj
- examples/005-dotnet-InProcessMemoryWithCustomHandler/005-dotnet-InProcessMemoryWithCustomHandler.csproj
- examples/006-dotnet-CustomHandlerAsAService/006-dotnet-CustomHandlerAsAService.csproj
- examples/102-using-azure-cognitive-search/102-using-azure-cognitive-search.csproj
- examples/103-using-qdrant/103-using-qdrant.csproj
- examples/104-dotnet-ExtractTextFromDocs/104-dotnet-ExtractTextFromDocs.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
Updating SK package to latest [dotnet-0.24.230918.1-preview](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-0.24.230918.1-preview) and consequently Microsoft.CodeAnalysis.NetAnalyzers to 7.0.4
> Updating SK package to dotnet-0.24.230918.1-preview 

- dotnet/CoreLib/Pipeline/Queue/DevTools/SimpleQueues.cs
Address issue https://github.com/microsoft/semantic-memory/issues/61
> Flag messages being processed in SimpleQueues

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
SecretManager is not designed for Prod, and we should allow applications to set their UserSecretsId from the entry point assembly.
> Support SecretManager only in dev mode

- examples/200-dotnet-nl2sql/nl2sql.config/README.md
- examples/200-dotnet-nl2sql/nl2sql.console/KernelFactory.cs
Update default emedding model to `ada_002`
`ada_003` not yet publicly available
> NL2SQL Update default embedding model

- dotnet/CoreLib/CoreLib.csproj
For unit tests to cover "internal" code.
Change the syntax to work with signed assemblies.
> Allow unit testing of signed assemblies

- COMMUNITY.md
- CONTRIBUTING.md
- README.md
- docs/FAQ.md
- docs/SECURITY_FILTERS.md
- dotnet/CoreLib/Configuration/SemanticMemoryConfig.cs
- dotnet/CoreLib/Diagnostics/DefaultLogger.cs
- dotnet/CoreLib/Pipeline/IPipelineStepHandler.cs
- dotnet/Service/Program.cs
- dotnet/Service/README.md
- dotnet/nuget/NUGET.md
- dotnet/nuget/nuget-package.props
- examples/001-dotnet-Serverless/Program.cs
- examples/001-dotnet-Serverless/README.md
- examples/002-dotnet-WebClient/Program.cs
- examples/002-dotnet-WebClient/README.md
- examples/003-curl-calling-webservice/README.md
- examples/200-dotnet-nl2sql/nl2sql.console/Program.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Schema/SchemaProvider.cs
- examples/README.md
- tools/README.md
- tools/ask.sh
- tools/search.sh
- tools/upload-file.sh
Renaming the solution to the official name: Kernel Memory
This is the first PR, containing only non breaking changes, such as docs, links and such.
One or more PR will follow with the breaking changes.
> Renaming Semantic Memory to Kernel Memory (non breaking changes)

- examples/000-notebooks/001-upload-and-ask.ipynb
- examples/009-dotnet-custom-LLM/009-dotnet-custom-LLM.csproj
- examples/009-dotnet-custom-LLM/Program.cs
- examples/101-using-core-nuget/101-using-core-nuget.csproj
- examples/101-using-core-nuget/Program.cs
New nugets available, with new naming and support for volatile data.
Update examples using nuget packages.
Update notebook mentioning the volatile memory.
> Update all examples using nugets

- dotnet/CoreLib/CoreLib.csproj
- examples/200-dotnet-nl2sql/nl2sql.console/KernelFactory.cs
- examples/200-dotnet-nl2sql/nl2sql.console/Nl2SqlConsole.cs
- examples/200-dotnet-nl2sql/nl2sql.console/Program.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/Schema/SchemaProvider.cs
- examples/200-dotnet-nl2sql/nl2sql.library/SqlQueryGenerator.cs
Prepare for updating chat-copilot with current version of kernel-memory: https://github.com/microsoft/chat-copilot
Also updated NL2SQL example.
Verified both `Memory Service` and `NL2SQL `example
Regular maintenance
> Update SemanticKernel to 1.0.0-beta4 package

- README.md
- examples/002-dotnet-WebClient/002-dotnet-WebClient.csproj
- examples/002-dotnet-WebClient/Program.cs
Provide helpful badges in the README about the project.
README badges in a similar format as Semantic Kernel.
> Add README badges

- dotnet/CoreLib/AI/AzureOpenAI/DependencyInjection.cs
- dotnet/CoreLib/CoreLib.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
Stay in sync with the latest and greatest!
**VERIFIED**
> Update Semantic Kernel To Beta7 Package

- Directory.Packages.props
- service/Core/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- service/tests/azure-cognitive-search-tests/Program.cs
Update to the latest `Azure.Search.Documents` version.
Update package version and fix associated regressions (mostly naming).
> Bump Azure.Search.Documents from 11.5.0-beta.5 to 11.5.0

- COMMUNITY.md
- README.md
- extensions/AzureAIDocIntel/README.md
- extensions/AzureAISearch/README.md
- extensions/AzureBlobs/README.md
- extensions/AzureOpenAI/README.md
- extensions/AzureQueues/README.md
- extensions/LlamaSharp/README.md
- extensions/OpenAI/README.md
- extensions/Postgres/Postgres/Db/PostgresDbClient.cs
- extensions/Postgres/README.md
- extensions/Qdrant/README.md
- extensions/RabbitMQ/README.md
- service/tests/FunctionalTests/FunctionalTests.csproj
- service/tests/FunctionalTests/VectorDbComparison/TestCosineSimilarity.cs
- service/tests/FunctionalTests/appsettings.json
* Fix Postgres search by similarity SQL to sort records by similarity (descending)
* Update docs, add links to nuget packages
> Fix Postgres records ordering + Docs update

- clients/dotnet/SemanticKernelPlugin/MemoryPlugin.cs
- Add support for filtering memories by tags in memory.search and memory.ask methods.
> Add support for filtering memories by tags in SK Plugin

- Directory.Packages.props
- extensions/Postgres/Postgres.UnitTests/PostgresConfigTests.cs
- extensions/Postgres/Postgres.UnitTests/Usings.cs
- extensions/Qdrant/Qdrant.UnitTests/FilteringTest.cs
- extensions/Qdrant/Qdrant.UnitTests/Qdrant.UnitTests.csproj
- extensions/Qdrant/Qdrant.UnitTests/ScrollVectorsRequestTest.cs
- service/Core/KernelMemoryBuilder.cs
- service/tests/Core.UnitTests/Core.UnitTests.csproj
- service/tests/Core.UnitTests/KernelMemoryBuilderTest.cs
> bug fix: builder checking for incorrect interface

- Directory.Packages.props
- KernelMemory.sln
- README.md
- docs/index.md
- extensions/SQLServer/README.md
- extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs
- extensions/SQLServer/SQLServer.FunctionalTests/SQLServer.FunctionalTests.csproj
- extensions/SQLServer/SQLServer.FunctionalTests/Startup.cs
- extensions/SQLServer/SQLServer.FunctionalTests/Usings.cs
- extensions/SQLServer/SQLServer.FunctionalTests/appsettings.json
- tools/run-mssql.sh
I developped a MSSQL Server connector for Semantic Kernel and also a connector for Kernel Memory.
> Add link to MSSQL Server plugin

- KernelMemory.sln.DotSettings
- examples/002-dotnet-SemanticKernelPlugin/002-dotnet-SemanticKernelPlugin.csproj
- examples/203-dotnet-using-core-nuget/203-dotnet-using-core-nuget.csproj
- service/Service/Service.csproj
- service/tests/Core.UnitTests/Core.UnitTests.csproj
- service/tests/Core.UnitTests/KernelMemoryBuilderTest.cs
* Update Service dependencies (KM only)
* Fix a few build warnings
> Upgrade Service with latest KM dependencies

- service/Service/ServiceConfiguration.cs
> Fix Service DI settings, support old config keys

- Directory.Packages.props
- KernelMemory.sln
- KernelMemory.sln.DotSettings
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/DefaultTests.cs
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/Elasticsearch.FunctionalTests.csproj
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/Startup.cs
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/Usings.cs
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/appsettings.json
- extensions/Elasticsearch/README.md
- tools/run-qdrant.sh
Test coverage for third party extension
> Functional tests for Elasticsearch extension

- Directory.Packages.props
* Downgrade DocumentFormat.OpenXml to fix #265 
* Upgrade MSSQL package tested by functional tests
> Fix #265 for Excel files

- service/Abstractions/AppBuilders/ServiceCollectionPool.cs
When working with a pool of service collections, some operations like access by position and deletion are not allowed because the underlying data structure might have multiple collections and the operation would lead to inconsistent results.
However:
* deletion can be considered an idempotent operation, thus allowed
* in most scenarios the pool contains only one collection, in which case there is not risk
* allow all operations when the pool contains only one collection. When working with multiple collections the user must prepare the service collection before passing it to KMBuilder ctor
* allow delete operations
> Improve ServiceCollectionPool, fix for 288

- Directory.Packages.props
- service/Core/MemoryServerless.cs
- service/Core/Pipeline/BaseOrchestrator.cs
- service/Core/Pipeline/DistributedPipelineOrchestrator.cs
- tools/InteractiveSetup/InteractiveSetup.csproj
Upgrade to latest Abstractions 0.27 and enable related code improvements
> Upgrade to latest Abstractions 0.27

- Directory.Packages.props
- examples/002-dotnet-SemanticKernelPlugin/002-dotnet-SemanticKernelPlugin.csproj
Upgrade Polly, HtmlAgilityPack, SK, Json, CodeAnalyzers
> Upgrade misc dependencies

- extensions/Redis/Redis/RedisMemory.cs
- service/Service/Program.cs
- service/Service/Service.csproj
- service/Service/ServiceConfiguration.cs
- service/Service/appsettings.json
- tools/InteractiveSetup/Main.cs
* Adding hooks for adding Redis as a provider for the service project (adding additional dialogs to setup)
* Noticed RedisMemory was pulling back embeddings from Redis (not presenting to user but I noted large allocations when there shouldn't be!), adding appropriate bits to query to prevent it.
> Redis service hooks, remove embeddings when not needed

- docs/extensions/memory-db/qdrant.md
Updated typo for better readability
> Updated typo for better readability

- README.md
- examples/003-dotnet-Serverless/003-dotnet-Serverless.csproj
- examples/003-dotnet-Serverless/Program.cs
- examples/003-dotnet-Serverless/file7-submarine.html
- service/Abstractions/Pipeline/MimeTypes.cs
- service/Core/DataFormats/WebPages/HtmlDecoder.cs
- service/Core/Handlers/TextExtractionHandler.cs
Add support for importing HTML files.
> Support HTML files

- docs/quickstart.md
Fix broken link issue from quick start page , refer to main branch for any example
> Fix broken link in quick start page

- Directory.Packages.props
- examples/206-dotnet-configuration-and-logging/206-dotnet-configuration-and-logging.csproj
- service/Core/Handlers/TextExtractionHandler.cs
Upgrade Core to use latest Abstractions package with new mime type for HTML files.
> Upgrade Core to Abstractions 0.30

- examples/202-dotnet-custom-handler-as-a-service/202-dotnet-custom-handler-as-a-service.csproj
- examples/202-dotnet-custom-handler-as-a-service/MyHandler.cs
- examples/202-dotnet-custom-handler-as-a-service/Program.cs
- service/Abstractions/Pipeline/IPipelineOrchestrator.cs
- service/Core/Handlers/DependencyInjection.cs
- service/Core/Pipeline/BaseOrchestrator.cs
- service/Core/Pipeline/DistributedPipelineOrchestrator.cs
- service/Core/Pipeline/InProcessPipelineOrchestrator.cs
- service/Service/Program.cs
- service/Service/appsettings.json
- tools/InteractiveSetup/AppSettings.cs
- tools/InteractiveSetup/Main.cs
- tools/InteractiveSetup/UI/QuestionWithOptions.cs
- tools/InteractiveSetup/UI/SetupUI.cs
Address #340, allow to run the service with serverless settings.
Fix config syntax error introduced in #341
Requires a release and follow up PR to upgrade Core.
> Fix service, allow to work with serverless config

- docs/FAQ.md
Link to security filters is broken
Fixes link to security filters when deployed to https://microsoft.github.io/
> Fix broken link

- service/Abstractions/DataFormats/FileContent.cs
- service/Abstractions/DataFormats/IContentDecoder.cs
- service/Abstractions/Pipeline/MimeTypes.cs
See https://github.com/microsoft/kernel-memory/pull/398#issuecomment-2052075589. This PR updates the **Abstractions** project that is needed to support custom Content Decoders.
> Update Abstractions to support custom Content Decoders

- Directory.Packages.props
- examples/002-dotnet-SemanticKernel-plugin/002-dotnet-SemanticKernel-plugin.csproj
- examples/203-dotnet-using-core-nuget/203-dotnet-using-core-nuget.csproj
* Azure Identity security fix, see https://github.com/advisories/GHSA-wvxc-855f-jvrv
* SK upgrade
* KM upgrade
* LLamaSharp upgrade, tested with llama-2-13b.Q5_K_M.gguf
* XUnit upgrade
> Upgrade Azure Identity (security) and other packages

- examples/001-dotnet-WebClient/Program.cs
- infra/README.md
- infra/main.bicep
- infra/main.json
- infra/modules/ai-search.bicep
- infra/modules/cognitive-services.bicep
- infra/modules/container-app.bicep
- infra/modules/managed-identity.bicep
- infra/modules/storage.bicep
> Bicep optimizations

- service/Abstractions/AppBuilders/ServiceCollectionPool.cs
- service/Abstractions/Configuration/TextPartitioningOptions.cs
- service/Abstractions/Diagnostics/ArgumentNullExceptionEx.cs
- service/Abstractions/Diagnostics/ArgumentOutOfRangeExceptionEx.cs
- service/Abstractions/Diagnostics/DefaultLogger.cs
- service/Abstractions/Diagnostics/NullableAttribute.cs
- service/Abstractions/KernelMemoryBuilderExtensions.cs
- service/Abstractions/Models/Document.cs
- service/Abstractions/Models/TagCollectionExtensions.cs
- service/Abstractions/Pipeline/DataPipeline.cs
- service/Abstractions/Search/SearchClientConfig.cs
Introduce new helpers to provide better error messages and reduce code, compatibly with .NET Standard 2.0
Use new code in the Abstractions package.
Fix some exception types uses in Abstractions.
> Revisit error messages for readability

- infra/main.json
- infra/modules/cognitive-services-openAI.bicep
- infra/modules/storage.bicep
> Infrastructure security improvements 

- service/Abstractions/KernelMemoryBuilderExtensions.cs
This PR fixes the issue described at https://github.com/microsoft/kernel-memory/pull/424#issuecomment-2075035387.
> Fix KernelMemoryBuilderExtensions

- Directory.Packages.props
- examples/002-dotnet-SemanticKernel-plugin/002-dotnet-SemanticKernel-plugin.csproj
* Upgrade KM Abstractions
* Upgrade SK to 1.9.0
* Upgrade XUnit DI
> Upgrade KM Abstractions

- service/Abstractions/MemoryStorage/IndexNotFound.cs
Add new IndexNotFound exception to be used by memory dbs and clients
> Add new IndexNotFound exception

- KernelMemory.sln
- examples/111-dotnet-azure-ai-hybrid-search/111-dotnet-azure-ai-hybrid-search.csproj
- examples/111-dotnet-azure-ai-hybrid-search/Program.cs
- examples/111-dotnet-azure-ai-hybrid-search/appsettings.json
- extensions/AzureAISearch/AzureAISearch/AzureAISearchConfig.cs
- extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
- service/Core/Search/SearchClient.cs
- service/Service/appsettings.json
- tools/InteractiveSetup/Services/AzureAISearch.cs
- tools/InteractiveSetup/UI/DictionaryExtensions.cs
- tools/InteractiveSetup/UI/SetupUI.cs
Already described in issue #159 
The main idea is to support Azure AI search Hybrid search.
Already described in issue #159
> Add Azure AI Search hybrid search support

- Directory.Packages.props
- KernelMemory.sln
- KernelMemory.sln.DotSettings
- README.md
- extensions/TikToken/README.md
- extensions/TikToken/TikToken.UnitTests/Startup.cs
- extensions/TikToken/TikToken.UnitTests/TikToken.UnitTests.csproj
- extensions/TikToken/TikToken.UnitTests/TikTokenTokenizersTest.cs
- extensions/TikToken/TikToken/TikToken.csproj
- extensions/TikToken/TikToken/TikTokenGPT2Tokenizer.cs
- extensions/TikToken/TikToken/TikTokenGPT3Tokenizer.cs
- extensions/TikToken/TikToken/TikTokenGPT4Tokenizer.cs
New tokenizers, up to date for GPT4
> New TikToken tokenizers package

- KernelMemory.sln.DotSettings
- clients/dotnet/WebClient/MemoryWebClient.cs
- clients/dotnet/WebClient/WebClient.csproj
- examples/006-curl-calling-webservice/README.md
- extensions/AzureBlobs/AzureBlobs.csproj
- extensions/AzureBlobs/AzureBlobsStorage.cs
- extensions/MongoDbAtlas/MongoDbAtlas/MongoDbAtlas.csproj
- extensions/MongoDbAtlas/MongoDbAtlas/MongoDbAtlasStorage.cs
- extensions/TikToken/TikToken/TikToken.csproj
- nuget-package.props
- service/Abstractions/Constants.cs
- service/Abstractions/ContentStorage/IContentStorage.cs
- service/Abstractions/IKernelMemory.cs
- service/Abstractions/Models/StreamableFileContent.cs
- service/Abstractions/Pipeline/IPipelineOrchestrator.cs
- service/Core/ContentStorage/DevTools/SimpleFileStorage.cs
- service/Core/MemoryServerless.cs
- service/Core/MemoryService.cs
- service/Core/Pipeline/BaseOrchestrator.cs
- tools/upload-file.sh
Supporting abstractions for new File Download feature. See PR #415
* New version 0.40
* Breaking changes on storage interface
* New methods on orchestration interface
* New methods on memory interface
> New abstractions to support file download

- service/Core/Pipeline/BaseOrchestrator.cs
See https://github.com/microsoft/kernel-memory/issues/475.
> Add missing 'using' keyword for StreamableFileContent

- clients/dotnet/WebClient/MemoryWebClient.cs
> Reset stream position before posting to server

- applications/evaluation/Distribution.cs
- applications/evaluation/README.md
- applications/evaluation/TestSet/TestSetItem.cs
- applications/evaluation/TestSetEvaluator.cs
- applications/evaluation/TestSetEvaluatorBuilder.cs
- applications/evaluation/TestSetGenerator.cs
- applications/evaluation/TestSetGeneratorBuilder.cs
- examples/401-evaluation/Program.cs
- Add builders for generator and evaluators
- Use DI to create engin classes
- Update sample code + README
> KM evaluation refactorings

- docs/extensions/memory-db/postgres.md
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/appsettings.json
- extensions/Postgres/Postgres.FunctionalTests/appsettings.json
- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
- extensions/Postgres/README.md
- service/Service/appsettings.json
- service/tests/Core.FunctionalTests/appsettings.json
see https://github.com/microsoft/kernel-memory/issues/598
Improve docs and default settings, adding `Database` param.
Handle specific error with additional error logs to help resolution.
> Postgres: improve docs and code handling “db not found” scenario

- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
See https://github.com/microsoft/kernel-memory/issues/649
Remove "0x00" from chunks content written to Postgres.
> Fix for Postgres not supporting 0x00 on text fields

- extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
see https://github.com/microsoft/kernel-memory/issues/686
adding "size" limit as well if there are not filters defined
> Fix search results limiting in AzureAiSearchMemory

- service/Abstractions/Context/IContext.cs
See https://github.com/microsoft/kernel-memory/issues/701.
> Fix Custom Context types inconsistencies

- service/Service/Program.cs
a simple health probe to respond 200 after all checks
> health probe

- Directory.Build.props
- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
Add explicit call to disconnect from Postgres, before the call to DisposeAsync.
See also https://github.com/microsoft/kernel-memory/issues/679
> Potgres: add explicit call to disconnect

- extensions/SQLServer/SQLServer/SqlServerMemory.cs
This PR fixes an issue when trying to delete a document from SQL Server Memory.
The [DeleteDocumentHandler](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/DeleteDocumentHandler.cs) class calls the memory `GetListAsync` method and then deletes each returned records, using an async enumeration:
https://github.com/microsoft/kernel-memory/blob/2ff894c99d30531fe83a9134c35ec4608583ef59/service/Core/Handlers/DeleteDocumentHandler.cs#L45-L54
The issue is related to how records are returned in [SqlServerMemory.GetListAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L235):
https://github.com/microsoft/kernel-memory/blob/2ff894c99d30531fe83a9134c35ec4608583ef59/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L2 …
> Fix transaction problem in SQL Server Memory DeleteAsync method

- .gitignore
- KernelMemory.sln
- azure.yaml
- infra/AZD.md
- infra/main.parameters.json
Adding AZD support
Adding azd support
Updating AZD.md documentation
> Adding support for Azure Developer CLI (AZD)

- docs/azure/architecture.md
> grammar mistake in architecture.md

- Directory.Build.props
- Directory.Packages.props
- extensions/OpenAI/OpenAI/Tokenizers/DefaultGPTTokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT2Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT3Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT4Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT4oTokenizer.cs
- service/Core/Core.csproj
Azure:
* Azure.Storage.Blobs
* Azure.Storage.Queues
Document parsing:
* ClosedXML 0.102.3 -> 0.104.0-rc1
* DocumentFormat.OpenXml 2.20.0 -> 3.1.0
SK:
* Microsoft.SemanticKernel 1.18.2 -> 1.20.0
Misc:
* AWSSDK
* Microsoft.ML.Tokenizers
* OllamaSharp
* NRedisStack
> Upgrade packages, fix issue with OpenXml

- Directory.Build.props
- Directory.Packages.props
- applications/evaluation/Evaluation.csproj
SK => 1.21.1
Azure.Storage.Blobs => 12.22.1
HtmlAgilityPack => 1.11.66
OllamaSharp => 3.0.8
> Upgrade dependencies

- Directory.Packages.props
Upgraded **ClosedXML** package from 0.104.0-rc1 to 0.104.1 in the `Directory.Packages.props` file.
> Update ClosedXML package to version 0.104.1

- extensions/AzureQueues/AzureQueuesPipeline.cs
- service/Core/FileSystem/DevTools/VolatileFileSystem.cs
- service/Core/Pipeline/Queue/DevTools/Message.cs
- service/Core/Pipeline/Queue/DevTools/SimpleQueues.cs
- service/Core/Pipeline/Queue/DevTools/SimpleQueuesConfig.cs
- service/Service/appsettings.json
When working with simplequeue locally, it's difficult to debug errors missing some better pipeline retry logic.
* Add poison message handling to SimpleQueue
* Add backoff policy to SimpleQueue
> Simplequeue improvements: dead letters and backoff policy

- Directory.Packages.props
- examples/105-dotnet-serverless-llamasharp/105-dotnet-serverless-llamasharp.csproj
- extensions/LlamaSharp/LlamaSharp/LlamaSharp.csproj
- extensions/Postgres/Postgres/Postgres.csproj
- extensions/Redis/Redis/Redis.csproj
- service/Core/Core.csproj
* Upgrade packages
* Azure.Core (security fix)
* OllamaSharp (new nuget supports strong name)
* PdfPig (several fixes and improvements)
* Turn off CS8002 build warnings about strong names
> Upgrade packages + security fix

- .editorconfig
- Directory.Build.props
- Directory.Packages.props
- extensions/AzureOpenAI/Internals/AzureOpenAIClientBuilder.cs
- extensions/Ollama/Ollama/Ollama.csproj
- extensions/OpenAI/OpenAI/Internals/OpenAIClientBuilder.cs
- service/Abstractions/Abstractions.csproj
- service/Service.AspNetCore/Service.AspNetCore.csproj
- service/Service/Service.csproj
* Fix issue with missing implicit operator in System.ClientModel - https://github.com/microsoft/kernel-memory/issues/833
* Upgrade dependencies: Azure, SK, DI, etc.
* Remove explicit reference to System.Text.Json nuget, the package is used only by other libs
> Fix issue with missing implicit operator in System.ClientModel

- Directory.Packages.props
- service/Abstractions/Abstractions.csproj
Fixes the vulnerability reported at https://github.com/advisories/GHSA-8g4q-xg66-9fp4.
> Bump System.Text.Json to 8.0.5

- Directory.Packages.props
- SK 1.23.0
- OllamaSharp 3.0.14
- OpenXML 3.1.1
- MongoDB driver 2.30.0
> Upgrade SK, OllamaSharp, OpenXML, MongoDB

- .github/_typos.toml
- README.md
- swagger.json
- tools/InteractiveSetup/Context.cs
- tools/InteractiveSetup/Main.cs
- tools/InteractiveSetup/Services/SimpleFileStorage.cs
- tools/InteractiveSetup/Services/SimpleQueues.cs
- tools/InteractiveSetup/Services/SimpleVectorDb.cs
* Revisit README structure
* Add swagger.json to repo and link to visualize the file
* Allow to select "persistent" simplequeue/simplestorage/simplememory in setup tool
> Update README and improve simple/dev deps setup

- examples/200-dotnet-nl2sql/nl2sql.config/README.md
> Fix cd  path

- Directory.Build.props
- Directory.Packages.props
- extensions/AzureOpenAI/Internals/AzureOpenAIClientBuilder.cs
- extensions/OpenAI/OpenAI/OpenAITextGenerator.cs
Temporary workaround for Azure OpenAI SDK bug - service throttling handled incorrectly and causing incorrect HTTP status error
* https://github.com/Azure/azure-sdk-for-net/issues/46109
* https://github.com/microsoft/semantic-kernel/issues/8929
* https://github.com/microsoft/kernel-memory/issues/855
> Upgrade SK (incl. Azure OpenAI throttling fix) and OllamaSharp

- service/Core/Handlers/TextPartitioningHandler.cs
See https://github.com/microsoft/kernel-memory/discussions/885
> Add ChuckHeader for Markdown

- Directory.Packages.props
- service/tests/Core.FunctionalTests/DataFormats/Office/MsExcelDecoderTest.cs
**ClosedXML 0.104.2** solves a vulnerability issue in **System.IO.Packaging**: https://github.com/ClosedXML/ClosedXML/releases/tag/0.104.2
> Update ClosedXML package to version 0.104.2

- service/Core/MemoryStorage/MemoryRecordExtensions.cs
- service/Core/Search/AnswerGenerator.cs
- service/Core/Search/SearchClient.cs
- service/Core/Search/SearchClientResult.cs
Reduce SearchClient code duplication and complexity. This also paves the way for response streaming.
> Refactor search client

- Directory.Packages.props
- extensions/AzureQueues/AzureQueuesPipeline.cs
Updated the **OllamaSharp** package version in the `Directory.Packages.props` file from 4.0.11 to 4.0.17.
See https://github.com/microsoft/kernel-memory/issues/963
> Update OllamaSharp package to version 4.0.17

- Directory.Packages.props
- examples/204-dotnet-ASP.NET-MVC-integration/204-dotnet-ASP.NET-MVC-integration.csproj
- examples/301-discord-test-application/301-discord-test-application.csproj
- service/Core/ServiceCollectionExtensions.cs
- service/tests/Core.UnitTests/KernelMemoryBuilderTest.cs
Fix https://github.com/microsoft/kernel-memory/issues/977
> Support Build() options in KM builder extension methods

- extensions/Chunkers/Chunkers/PlainTextChunker.cs
Chinese text analysis requires proper handling of Chinese punctuation marks for more accurate text chunking. The original PlainTextChunker class was optimized for English punctuation, but this update adds support for Chinese punctuation, allowing the system to better handle Chinese content.
The following optimizations have been made to the PlainTextChunker class:
1. Added Chinese punctuation marks in delimiter groups with different priorities:
• ExplicitSeparators: Add end-of-sentence punctuation "。", "？", "！", "；", "："
• PotentialSeparators: Add "，", "、", and Chinese parentheses "（）", "【】", "《》"
• WeakSeparators1: Add "：", "，"
• Weak Separators2: Add Chinese quotation marks """ , """, "'", "'"
• WeakSeparators3: Add additional symbols "·", "—", "～"
2. The original separator priority …
> feat(TextChunker): Add support for Chinese separators

- service/Core/Core.csproj
> chore: update Core.csproj

- extensions/Chunkers/Chunkers/PlainTextChunker.cs
Added for more accumrate charactor segmentation for Japanese.
- PotentialSeparators: Add 「」『』
> adding a split character for Japanese
