microsoft/kernel-memory

- .github/workflows/publish.yaml
- dotnet/ClientLib/ClientLib.csproj
- dotnet/CoreLib/CoreLib.csproj
Temporary solution to publish CoreLib and ClientLib to Azure DevOps Artifacts Feed for internal consumption.
Will publish to a public feed/registry when ready.
Package names:
Microsoft.SemanticMemory.Core
Microsoft.SemanticMemory.Client
Versioning:
0.0.[RunId].[AttemptId]-preview
> Publish Nuget to ADO artifacts

- .vscode/settings.json
- dotnet/CoreLib/Pipeline/Queue/DependencyInjection.cs
- dotnet/CoreLib/Pipeline/Queue/FileBasedQueues/FileBasedQueue.cs
- dotnet/CoreLib/Pipeline/Queue/FileBasedQueues/FileBasedQueueConfig.cs
- dotnet/Service/appsettings.json
1. The project currently doesn't have VS code settings.
2. The file based queue doesn't create the directory automatically if it doesn't exist.
1. Add a settings.json under ./.vscode/.
2. Add an option to allow the file-based queue to create the directory automatically if it doesn't exist.
> Add vs code settings

- dotnet/InteractiveSetup/Main.cs
The directory prompt in InteractiveSetup was fixed to correctly ask for the directory where files should be stored.
> 🔧 Fix directory prompt in InteractiveSetup

- dotnet/CoreLib/Pipeline/DistributedPipelineOrchestrator.cs
- dotnet/CoreLib/Pipeline/InProcessPipelineOrchestrator.cs
This pull request improves error handling in the `TryAddHandlerAsync` and `AddHandlerAsync`. Currently, null checks and step name validation need reordering for better reliability.
I've repositioned null checks for the `handler` parameter to the start of both methods. This ensures `handler` is non-null before accessing properties. Step name validation now follows null checks, maintaining a consistent, safer order.
Please review these changes.
> Reordered null check and step name validation

- .github/_typos.toml
- README.md
- dotnet/Service/README.md
- examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/generatequery/skprompt.txt
- examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/isquery/skprompt.txt
- examples/200-dotnet-nl2sql/nl2sql.console/Nl2SqlConsole.cs
- examples/200-dotnet-nl2sql/nl2sql.console/appsettings.json
- examples/200-dotnet-nl2sql/nl2sql.library/SqlQueryGenerator.cs
- Prompts got shuffled up in all the code moves.
- Customers changing relevancy setting as they experiment with sandbox
- Unreverse prompts
- Make relevancy a configurable option (not hardcoded): `MinSchemaRelevance`
> Unreverse prompts and introduce relevance option (not hardcoded)

- dotnet/CoreLib/AI/AzureOpenAI/DependencyInjection.cs
- dotnet/CoreLib/AI/OpenAI/DependencyInjection.cs
- dotnet/CoreLib/AI/Tokenizers/GPT3/GPT3Settings.cs
- dotnet/CoreLib/ContentStorage/EmbeddingFileContent.cs
- dotnet/CoreLib/CoreLib.csproj
- dotnet/CoreLib/Handlers/GenerateEmbeddingsHandler.cs
- dotnet/CoreLib/Handlers/SaveEmbeddingsHandler.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemoryRecord.cs
- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
- dotnet/CoreLib/MemoryStorage/ISemanticMemoryVectorDb.cs
- dotnet/CoreLib/MemoryStorage/MemoryRecord.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/Client/Http/HttpRequest.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/Client/QdrantPoint.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/QdrantMemory.cs
- dotnet/CoreLib/Search/SearchClient.cs
- dotnet/CoreLib/Text/ReadOnlyMemoryConverter.cs
- examples/102-using-azure-cognitive-search/Program.cs
- examples/103-using-qdrant/Program.cs
- examples/200-dotnet-nl2sql/nl2sql.console/KernelFactory.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
- tests/FunctionalTests/VectorDbComparison/TestCosineSimilarity.cs
The latest versions of Semantic Kernel have breaking changes which prevents consumers from updating past the version Semantic Memory targets. This changes updates the Semantic Kernel version and fixes associated regressions.
- Update Semantic Kernel dependency to [0.21.230828.2-preview](https://www.nuget.org/packages/Microsoft.SemanticKernel/0.21.230828.2-preview).
- Fix `Embedding` -> `ReadOnlyMemorySpan` and `ILogger` -> `ILoggerFactory` regressions
- Refactor `ReadOnlyMemoryConverter` to a shared location
> Update Semantic Kernel to 0.21.230828.2-preview

- dotnet/CoreLib/AI/Embedding.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/CoreLib/MemoryStorage/ISemanticMemoryVectorDb.cs
- tests/FunctionalTests/VectorDbComparison/TestCosineSimilarity.cs
When using vector search with `VectorMetricType.Cosine`, Azure Cognitive Search search result score is expressed as Cosine Distance. The value `minRelevanceScore` passed to `ISemanticMemoryVectorDb` is expressed as Cosine Similarity, so it's important to transform the values during the comparison and when returning results to users.
Formulas:
```csharp
double DistanceToSimilarity(double distance)
{
return 1 - (1 - distance) / distance;
}
double SimilarityToDistance(double similarity)
{
return 1 / (2 - similarity);
}
```
> Azure Cognitive Search: cosine distance and cosine similarity

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
- dotnet/CoreLib/CoreLib.csproj
The config builder currently only read configs from appsettings.*.json.
Enable the Service and CoreLib to read from user secrets and environment variables.
> Read config from env and secrets

- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
The min relevance score was not taken into account in the simple vector db. This will cause the simple vector DB to return all records all the time.
Consider min relevance score in simple vector db.
> Consider min relevance score in simple vector db

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
We are seeing cases where the document summarization is being provided instead of the relevant chunk:
```
0.79480314 {"file":"Building 34_35 Orientation.pdf","emb_src_file":"Building 34_35 Orientation.pdf.summarize.0.txt"
0.7932581 {"file":"Building 34_35 Orientation.pdf","emb_src_file":"Building 34_35 Orientation.pdf.partition.1.txt"
0.78576535 {"file":"Building 34_35 Orientation.pdf","emb_src_file":"Building 34_35 Orientation.pdf.partition.0.txt"
```
Chat-Copilot would like the option to *not* introduce the document summary until we can explore the feature further.  At this point it only servers to create an additional false-positive target with zero to none added value.
> Allow skip of summarize handler during client setup.

- dotnet/CoreLib/CoreLib.csproj
- examples/101-using-core-nuget/101-using-core-nuget.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
One of the last changes to #43 removed the CPM opt out which fixed warnings but introduced the error `error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion`.
Add an explicit version override to project specific packages to fix CPM errors.
> Fix CPM errors

- dotnet/CoreLib/CoreLib.csproj
The `Microsoft.SemanticKernel` package currently includes dependencies on numerous other SK related packages for convenience (planners, retry, etc.). However, SM only uses a small subset of these. This leads to unnecessary dependencies when users add the SM package to their projects if they are selectively choosing different SK packages.
Note that `Nl2Sql.Library` is left alone to continue referencing the full SK package as it's an example scenario.
This change removes the `Microsoft.SemanticKernel` reference and replaces it with references to `Microsoft.SemanticKernel.Core` and `Microsoft.SemanticKernel.Connectors.AI.OpenAI`, which are the only two required dependencies. In the future, SM can add more SK related packages as and when they are needed. This approach reduces unnecessary …
> Only reference necessary SK packages

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
- dotnet/CoreLib/Configuration/SemanticMemoryConfig.cs
- dotnet/Service/appsettings.json
The default pipeline steps defined in appsettings.*.json and appsettings.json were not properly loaded and propagated when using DI.
Fix for https://github.com/microsoft/semantic-memory/issues/64
Fix: .NET IConfiguration doesn't support array override (when using multiple config sources): in fact arrays are merged so a shorter list in "appsettings.development.json" would not replace a longer list in "appsettings.json", but only replace the initial values. The list of default steps in appsettings.json is now empty, with defaults set via code. Values in appsettings.*.json now are properly loaded replacing the defaults.
SM config is also now stored in the service collection, so SemanticMemoryConfig can be injected via DI. Before the value passed by DI would be null, and the the pipeline …
> Fix use of DefaultSteps from config file

- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
- dotnet/CoreLib/AppBuilders/ServiceCollectionPool.cs
- examples/007-aspnet-mvc-integration/007-aspnet-mvc-integration.csproj
- examples/007-aspnet-mvc-integration/Controllers/MemoryController.cs
- examples/007-aspnet-mvc-integration/MyOcrEngine.cs
- examples/007-aspnet-mvc-integration/Program.cs
- examples/007-aspnet-mvc-integration/appsettings.json
When an application like ASP.NET shares with the memory builder the local service collection, the user might want all the memory dependencies to be injected into it. 
E.g. methods like `WithCustomImageOcr` inject dependencies into the service collection used by the memory, but not the one used by the end user application:
```csharp
var builder = WebApplication.CreateBuilder(args);
ISemanticMemoryClient memory = new MemoryClientBuilder(builder.Services)
.WithOpenAIDefaults(Env.Var("OPENAI_API_KEY"))
.WithCustomImageOcr(new MyOcrEngine())
.Build();
```
and a controller won't see the OCR engine, unless that is registered also in builder.Services
```csharp
[ApiController]
[Route("[controller]")]
public class MemoryController : ControllerBase
{
private readonly IOcrEngine _ocr;
public …
```
> Allow to share memory dependencies with external applications e.g. ASP.NET

- dotnet/ClientLib/Constants.cs
- dotnet/ClientLib/ISemanticMemoryClient.cs
- dotnet/ClientLib/MemoryWebClient.cs
- dotnet/ClientLib/Models/DeleteAccepted.cs
- dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
- dotnet/CoreLib/ContentStorage/AzureBlobs/AzureBlobsStorage.cs
- dotnet/CoreLib/ContentStorage/DevTools/SimpleFileStorage.cs
- dotnet/CoreLib/ContentStorage/IContentStorage.cs
- dotnet/CoreLib/Diagnostics/Verify.cs
- dotnet/CoreLib/Handlers/DeleteIndexHandler.cs
- dotnet/CoreLib/Handlers/GenerateEmbeddingsHandler.cs
- dotnet/CoreLib/Handlers/SaveEmbeddingsHandler.cs
- dotnet/CoreLib/Handlers/SummarizationHandler.cs
- dotnet/CoreLib/Handlers/TextExtractionHandler.cs
- dotnet/CoreLib/Handlers/TextPartitioningHandler.cs
- dotnet/CoreLib/Memory.cs
- dotnet/CoreLib/MemoryService.cs
- dotnet/CoreLib/MemoryStorage/DevTools/ISimpleStorage.cs
- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
- dotnet/CoreLib/MemoryStorage/ISemanticMemoryVectorDb.cs
- dotnet/CoreLib/Pipeline/BaseOrchestrator.cs
- dotnet/CoreLib/Pipeline/DataPipeline.cs
- dotnet/CoreLib/Pipeline/DistributedPipelineOrchestrator.cs
- dotnet/CoreLib/Pipeline/IPipelineOrchestrator.cs
- dotnet/CoreLib/Pipeline/InProcessPipelineOrchestrator.cs
- dotnet/Service/Program.cs
- tests/FunctionalTests/ServerLess/IndexDeletionTest.cs
New API allowing apps to delete entire indexes.
New API in `ISemanticMemoryClient` to delete indexes.
New HTTP method allowing to delete indexes.
New handler responsible for deleting vectors and files in storage.
New logic allowing a pipeline not having a document ID (just the index name to delete).
New logic to delete storage directories after a pipeline is complete and the status file has been written.
New functional tests (with manual verifications).
Fix OpenAPI signature of DELETE methods.
> New API to delete indexes

- dotnet/CoreLib/DataFormats/WebPages/WebScraper.cs
This PR adds the Telemetry UserAgent constant to the Webscraper HttpClient. This should fix issue: https://github.com/microsoft/semantic-memory/issues/97
> Added user-agent header to WebScraper

- KernelMemory.sln.DotSettings
- dotnet/ClientLib/Constants.cs
- dotnet/ClientLib/Models/Document.cs
- dotnet/ClientLib/Models/FileCollection.cs
- dotnet/ClientLib/Models/TagCollection.cs
- dotnet/CoreLib/FileSystem/DevTools/DiskFileSystem.cs
- dotnet/CoreLib/FileSystem/DevTools/VolatileFileSystem.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemoryRecord.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/Client/QdrantPoint.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/QdrantMemory.cs
- dotnet/CoreLib/WebService/HttpDocumentUploadRequest.cs
- tests/FunctionalTests/ServerLess/ImportFilesTest.cs
- tests/UnitTests/Models/DocumentTest.cs
* Fix #120 
* Fix incorrect tag name validation, `:` char should not be allowed
* Improve files/paths validation error messages
Various improvements to input string validation
* Streams upload: fix bug, filename doesn't need to be a valid ID.
* Document ID: explicitly allow only alphanumeric (and some other chars).
* Tag: disallow ':' in tag names.
* Improve error messages to help debugging.
* Add tests.
> Various improvements to input string validation

- Directory.Packages.props
Upgrade Azure.Identity: fix CVE-2023-36414
Upgrade other packages:
* HtmlAgilityPack (used by handlers)
* RabbitMQ.Client (async pipelines)
* Xunit (tests)
* Roslynator (code analyzers)
* LLamaSharp (used only in examples)
* SqlClient (used only in examples)
> Upgrade Azure.Identity: fix CVE-2023-36414

- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/README.md
Cognitive Search API version `2023-10-01-Preview` defaults to `preFilter`. This makes the previously required KNN increase redundant and unnecessarily retrieving a larger than required result set.
From the [docs](https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-query?tabs=query-2023-10-01-Preview%2Cfilter-2023-10-01-Preview#vector-query-with-filter):
```text
In 2023-10-01-Preview, you can apply a filter before or after query execution. The default is pre-query. If you want post-query filtering instead, set the vectorFiltermode parameter.
In 2023-07-01-Preview, a filter in a pure vector query is processed as a post-query operation.
```
Fixes #92.
Fixes #125.
- Remove the KNN increase when filtering
- Set `VectorFilterMode` to `PreFilter` (default) for clarity
> Remove ACS KNN increase when filtering

- dotnet/nuget/nuget-package.props
- tests/FunctionalTests/TestHelpers/RedirectConsole.cs
Fix some errors occurring when running xunit tests with multi-threads and output redirection. The console output sometimes is collected when a test already completed, leading to an InvalidOperationException
> Fix intermittent xunit errors

- dotnet/CoreLib/Extensions/BinaryDataExtensions.cs
- dotnet/CoreLib/Handlers/SummarizationHandler.cs
- dotnet/CoreLib/Handlers/TextPartitioningHandler.cs
- tests/UnitTests/Extensions/BinaryDataExtensionsTest.cs
Optimize the hashing logic in some of the pipeline handlers.
- Add `BinaryDataExtensions.ToSHA256`
- Refactor the SHA256 calculation to use `ToMemory` on the `BinaryData` object which removes an array allocation
> Refactor SHA256 in CoreLib

- dotnet/ClientLib/IKernelMemory.cs
- dotnet/ClientLib/MemoryWebClient.cs
- dotnet/ClientLib/Models/MemoryFilter.cs
- dotnet/ClientLib/Models/MemoryQuery.cs
- dotnet/ClientLib/Models/SearchQuery.cs
- dotnet/CoreLib/Handlers/DeleteDocumentHandler.cs
- dotnet/CoreLib/Handlers/DeleteIndexHandler.cs
- dotnet/CoreLib/Memory.cs
- dotnet/CoreLib/MemoryService.cs
- dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
- dotnet/CoreLib/MemoryStorage/IVectorDb.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/Client/Http/SearchVectorsRequest.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/Client/QdrantClient.cs
- dotnet/CoreLib/MemoryStorage/Qdrant/QdrantMemory.cs
- dotnet/CoreLib/Search/SearchClient.cs
- dotnet/Service/Program.cs
- dotnet/nuget/nuget-package.props
- tests/FunctionalTests/TestHelpers/RedirectConsole.cs
- tests/FunctionalTests/VectorDbComparison/TestCosineSimilarity.cs
Refactor `minRelevance` logic:
- Remove `MemoryFilter.MinRelevance`
- Add optional argument `minRelevance` to `SearchAsync` and `AskAsync` and forward as necessary
Fixes #109.
Remove the unused `MemoryFilter.MinRelevance` property and instead follow the optional argument pattern.
BREAKING change.
> Fix/refactor minRelevance

- dotnet/ClientLib/Constants.cs
- dotnet/CoreLib/Configuration/KernelMemoryConfig.cs
- dotnet/Service/README.md
- dotnet/Service/appsettings.json
- examples/009-dotnet-custom-LLM/appsettings.json
- tests/FunctionalTests/ServerLess/FilteringTest.cs
The summary step currently doesn't bring much value to RAG while it slows down ingestion by default.
Remove the summarization step fomr the default pipeline, letting users choose when to use it.
This helps also new users trying KM for the first time, avoiding the long time required to generate summaries.
> Remove summary step from the default pipeline

- dotnet/CoreLib/CoreLib.csproj
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
SemanticKernel 1.0.0-beta5 was published during the update to beta4.  Delta is small.
> Update kernel-memory to Current Semantic-Kernel Package (beta5)

- dotnet/CoreLib/AI/AzureOpenAI/DependencyInjection.cs
- dotnet/CoreLib/CoreLib.csproj
- examples/200-dotnet-nl2sql/nl2sql.console/KernelFactory.cs
- examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
Aligns Kernel Memory with the latest version of Semantic Kernel.
Fixes #152.
Update to Microsoft.SemanticKernel 1.0.0-beta6 and fixes associated regressions.
> Update to SK 1.0.0-beta6

- dotnet/ClientLib/MemoryWebClient.cs
- dotnet/CoreLib/Configuration/KernelMemoryConfig.cs
- dotnet/CoreLib/Configuration/ServiceAuthorizationConfig.cs
- dotnet/CoreLib/KernelMemoryBuilder.cs
- dotnet/Service/Auth/HttpAuthHandler.cs
- dotnet/Service/Program.cs
- dotnet/Service/Service.csproj
- dotnet/Service/appsettings.json
When deploying the memory service, the instance and its data should protected requiring a client to be authorized.
This change allows to enable authorization on all the endpoints, requiring a client to pass one of two valid API keys.
When enabled, the API returns 401 is the API key is not provided, and 403 if an invalid API key is provided.
By default API keys are passed using the `Authorization` header, although this is configurable.
New configuration block in `appsettings.json`:
```json
"ServiceAuthorization": {
// Whether clients must provide some credentials to interact with the HTTP API
"Enabled": false,
// Currently "APIKey" is the only type supported
"AuthenticationType": "APIKey",
// HTTP header name to check
"HttpHeaderName": "Authorization",
// Define two separate API Keys, to …
```
> Allow to enable HTTP authorization on memory web service

- service/Abstractions/AI/Embedding.cs
Small tweak to optimize the cosine similarity logic.
Avoid allocating the array again by using `Span` over `ToArray()`.
> Use Span when checking cosine similarity

- .gitignore
- service/Core/MemoryStorage/Qdrant/Client/QdrantClient.cs
- service/tests/FunctionalTests/ServerLess/FilteringTest.cs
- service/tests/FunctionalTests/ServerLess/IndexListTest.cs
- service/tests/FunctionalTests/ServerLess/MissingIndexTest.cs
- service/tests/FunctionalTests/ServerLess/OpenAITest.cs
- service/tests/FunctionalTests/TestHelpers/BaseTestCase.cs
When using an index that doesn't exist, the final result should be consistent regardless of the memory DB selected.  E.g. see #95.
When using a non-existing index:
* Delete index: no error
* Delete document: no error
* Ask/Search: empty result
* Checking if a document is ready: return false
* Fetch document status: return null
* Importing documents: the index is created by "save-records" handler
Fixes #95
> Consistently handle "index not found" across different memory DBs

- examples/002-dotnet-SemanticKernelPlugin/Program.cs
I downloaded the latest build and I ran in a compilation issue of Program.cs in 002-dotnet-SemanticKernelPlugin
The problem is at lines 23 to 32, where the methods AddXXX should be replaced with WithXXX
-Add -> WithOpenAIChatCompletion
-Add -> WithAzureOpenAIChatCompletion
The solution didn't compile.
> 002-dotnet-SemanticKernelPlugin example: A couple of calls to KernelBuilder methods don't match the new names in SK rc3

- examples/001-dotnet-WebClient/Program.cs
- examples/003-dotnet-Serverless/Program.cs
- examples/205-dotnet-extract-text-from-docs/Program.cs
- service/Abstractions/Constants.cs
- service/Abstractions/Models/Citation.cs
- service/Abstractions/Models/MemoryAnswer.cs
- service/Abstractions/Models/SearchResult.cs
- service/Core/DataFormats/DocumentPage.cs
- service/Core/DataFormats/Pdf/PdfDecoder.cs
- service/Core/Handlers/SaveRecordsHandler.cs
- service/Core/Handlers/TextExtractionHandler.cs
- service/Core/Prompts/answer-with-facts.txt
- service/Core/Search/SearchClient.cs
- service/nuget-package.props
- service/tests/FunctionalTests/ServerLess/AIClients/LlamaSharpTextGeneratorTest.cs
- service/tests/FunctionalTests/ServerLess/FilteringTest.cs
- service/tests/FunctionalTests/ServerLess/MissingIndexTest.cs
- service/tests/FunctionalTests/Service/FilteringTest.cs
- service/tests/FunctionalTests/TestHelpers/BaseTestCase.cs
- service/tests/FunctionalTests/VectorDbComparison/TestMemoryFilters.cs
When using Search and Ask API, some source details are missing, e.g. Index name, Document ID, file ID, tags per partition, web pages URL.
These details can be useful to refine search and UIs.
* Change Search and Ask result schema to include: 
* Index name (`index`), Document ID (`documentId`), File ID (`fileId`)
* `noResult` boolean indicating whether there is a result or not, so clients don't need to parse text to figure it out
* `noResultReason` with a brief explanation about why there are no results
* When a memory is extracted from a web page, include the URL in the citations (`sourceUrl`)
* Move Tags from File to Partition, considering that tags can differ for synthetic data (breaking change)
* Added some new code to deal with page numbers, not in use yet. Future PR needed to include …
> Add more details to search/ask results

- service/Abstractions/Constants.cs
- service/Abstractions/Pipeline/DataPipeline.cs
- service/Core/Handlers/DeleteDocumentGeneratedFiles.cs
- service/Core/Handlers/DeleteGeneratedFilesHandler.cs
- service/Core/KernelMemoryBuilder.cs
- service/Core/Pipeline/BaseOrchestrator.cs
Added a new Handler that allows the deletion of the generated "physical" (disk, blob...) files after a document has been imported.
This should address this question: https://github.com/microsoft/kernel-memory/issues/107
This new handler as not been added to any default pipeline, so nothing changes for current clients. However, the Handler is not present, so it can be passed as _step_ when calling any of the current ```ImportDocumentAsync````
i.e:
```csharp
await memory.ImportDocumentAsync(
"sample-Wikipedia-Moon.txt",
steps: new[] { Constants.DeleteDocumentGeneratedFilesPipelineStepName });
```
@dluc this solution would give us the functionality we need, as would avoid any compliance issue with having enterprise docs out of M365. It's not a perfect solution, and I'm happy to make any …
> New handler added to allow the deletion of the generated files.

- service/Core/Configuration/Env.cs
**Before:** 
Since the Core project does not configure UserSecretId, it is not possible to retrieve the configuration from UserSecrets through Env.Var().
**After:** 
The places where Env.Var() is used are usually the entry points for application configuration. Specifying EntryAssembly or CallingAssembly can retrieve the configuration in UserSecrets in the current project, if UserSecretId is configured.
> Change the user secrets configuration source of Env.Var

- examples/004-dotnet-ServerlessCustomPipeline/Program.cs
- examples/201-dotnet-InProcessMemoryWithCustomHandler/Program.cs
- examples/203-dotnet-using-core-nuget/Program.cs
- examples/204-dotnet-ASP.NET-MVC-integration/Program.cs
- service/Abstractions/AppBuilders/ServiceCollectionPool.cs
- service/Abstractions/IKernelMemoryBuilder.cs
- service/Core/KernelMemoryBuilder.cs
- service/Service/.editorconfig
- service/Service/Auth/HttpAuthHandler.cs
- service/Service/KernelMemoryBuilderExtensions.cs
- service/Service/Program.cs
- service/Service/ServiceConfiguration.cs
- tools/InteractiveSetup/InteractiveSetup.csproj
- tools/InteractiveSetup/Main.cs
Reduce IKernelMemoryBuilder interface, moving `FromAppSettings` and `FromConfiguration` to extension methods used only by the web service. 
This work is required to easily support additional dependencies not part of Core, e..g Postgres, without having to add dependencies to the Core nuget.
> Reduce IKernelMemoryBuilder interface, prep for additional storage connectors

- clients/dotnet/WebClient/MemoryWebClient.cs
- nuget-package.props
- service/Abstractions/Constants.cs
- service/Abstractions/Models/TagCollection.cs
- service/Core/WebService/HttpDocumentUploadRequest.cs
- service/Service/Service.csproj
- service/tests/ServiceFunctionalTests/DocumentUploadTest.cs
Improve API schema used to specify document tags.
Use a specific form field name for tags.
> Pass Tags using an explicit form field

- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/AzureOpenAI/AzureOpenAITextGenerator.cs
- extensions/AzureOpenAI/DependencyInjection.cs
- extensions/OpenAI/DependencyInjection.cs
- extensions/OpenAI/OpenAITextEmbeddingGenerator.cs
- extensions/OpenAI/OpenAITextGenerator.cs
For some businesses and their teams, there is often a need for more detailed and personalized configuration when using HttpClient to make network requests. Semantic Kernel already supports this. However, inconsistencies in operation were found when using Semantic Kernel and Kernel Memory synchronously. To address this issue, this improvement PR has been submitted, aiming to standardize the corresponding features to be on par with the design of Semantic Kernel. Reference: https://github.com/microsoft/semantic-kernel/pull/743
Introduce a new optional parameter named `httpClient`. By setting its default value to `null`, we ensure that the existing user's code remains unaffected and backward compatible.
> Allow passing custom HttpClient

- Directory.Packages.props
- KernelMemory.sln
- extensions/Redis/DependencyInjection.cs
- extensions/Redis/README.md
- extensions/Redis/Redis.csproj
- extensions/Redis/RedisConfig.cs
- extensions/Redis/RedisEmbeddingExtensions.cs
- extensions/Redis/RedisException.cs
- extensions/Redis/RedisMemory.cs
- service/tests/redis-tests/MockEmbeddingGenerator.cs
- service/tests/redis-tests/Program.cs
- service/tests/redis-tests/redis-tests.csproj
- tools/README.md
- tools/run-redis.sh
Implements #199 
Adds [Redis Vector Search](https://redis.io/docs/get-started/vector-database/) as an `IMemoryDb`.
Couple of high-level notes:
1. Tags in Redis need to be pre-defined if you want to filter on them. Also the way the Redis stores tags in a hash means you use a separator character to mark individual tags e.g. `'topics': ['tech', 'microsoft', 'redis']` would be stored in Redis as `HSET key topics tech,microsoft,redis` then when you search on the tag e.g. `@topics:{redis}` it will match. What this means from the user's perspective if that if they want to use tags they will need to predefined it before they create the index. I've added a bit to the dependency injection to note this. I also added as a blurb in the README (don't know if there's anywhere else to add those notes to …
> RedisMemory

- extensions/OpenAI/DependencyInjection.cs
The order of text model/embedding model max tokens was inverted, allowing to use only 8K tokens with GPT3.5-16k and allowing to pass 16k tokens to Ada2, which supports only 8k.
> Fix default OpenAI settings

- docs/how-to/custom-partitioning.md
- docs/how-to/custom-pipelines.md
- docs/how-to/custom-prompts.md
- docs/how-to/hugging-face.md
- service/Core/Configuration/InternalConstants.cs
- service/Core/Handlers/TextPartitioningHandler.cs
When using a custom embedding generator that supports less than the default partitioning settings, the app shows an error without providing a path to resolution.
Previous error message:
> The configured partition size (1000 tokens) is too big for one of the embedding generators in use. The max value allowed is 256 tokens
New error message:
> The configured partition size (1000 tokens) is too big for one of the embedding generators in use. The max value allowed is 256 tokens. Consider changing the partitioning options, see https://microsoft.github.io/kernel-memory/how-to/custom-partitioning for details.
> Improve error message used when token count is too high (+ docs)

- extensions/Redis/README.md
- extensions/Redis/Redis/RedisConfig.cs
- extensions/Redis/Redis/RedisMemory.cs
- tools/README.md
- tools/run-redis.sh
Couple follow on items from #208 
1. making vector algorithm configurable (defaulting to HNSW)
2. Updating Readme to explain the presence of Redis Insight
3. Changing tooling to launch redis-stack with Redis insight as well
4. throwing an exception when you attempt to add a tag with the defined separator in it.
> Redis Memory follow up

- Directory.Packages.props
The upgrade to version 0.9.5 of FreeMindLabs.KernelMemory.Elasticsearch resolved a series of issues:
-Filters with multiple tags resulted in only the last tag to be considered.
-Ensured that deletes and upserts wait for the data to be available for search before continuing. Tests would fail sporadically.
The changes are in the FMKL nuget, but the following links are related to the "eventually consistent" timing issue:
1. https://stackoverflow.com/questions/40676324/elasticsearch-updates-are-not-immediate-how-do-you-wait-for-elasticsearch-to-fi
2. https://www.jillesvangurp.com/blog/2014-12-04-eventual-consistency-now-using-elasticsearch-and-redis.html
> -Changed the reference to the latest Elasticsearch plugin nuget (0.9.5)

- service/Core/MemoryStorage/DevTools/SimpleVectorDb.cs
- service/tests/Core.UnitTests/MemoryStorage/DevTools/SimpleVectorDbTest.cs
Bug #267: SimpleVectorDb is not considering all document for computing cosine similarity
Fix: consider all records
> Fix #267: SimpleVectorDb is not considering all document for computing cosine similarity

- examples/001-dotnet-WebClient/Program.cs
- examples/003-dotnet-Serverless/Program.cs
Fix a bad web page reference in the example
was: https://raw.githubusercontent.com/microsoft/kernel-memory/main/docs/SECURITY_FILTERS.md
changed to: https://raw.githubusercontent.com/microsoft/kernel-memory/main/docs/security/security-filters.md
> Fix the reference to security-filters.md

- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/AzureOpenAI/AzureOpenAITextGenerator.cs
Allow to use manual token credentials also with AzureOpenAITextEmbeddingGenerator.
see #290
> Support ManualTokenCredential in AzureOpenAITextEmbeddingGenerator

- extensions/RabbitMQ/RabbitMQPipeline.cs
- extensions/RabbitMQ/RabbitMqConfig.cs
- service/Service/appsettings.json
- tools/InteractiveSetup/AppSettings.cs
- tools/InteractiveSetup/Main.cs
In a scenario where a RabbitMQ cluster is shared between multiples applications it would be nice to be allowed to connect into an isolated virtual host to better organize the queues and exchanges in the cluster.
Adding the ``VirtualHost`` property in the RabbitMQ configuration and passing it to the RabbitMQ Client
> Allowing the configuration of the virtual host of RabbitMQ

- KernelMemory.sln.DotSettings
- extensions/AzureAISearch/AzureAISearch.FunctionalTests/appsettings.json
- extensions/AzureAISearch/AzureAISearch.UnitTests/AzureAISearchFilteringTest.cs
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/DefaultTests.cs
- extensions/Elasticsearch/Elasticsearch.FunctionalTests/appsettings.json
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/LlamaSharpTextGeneratorTest.cs
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/appsettings.json
- extensions/Postgres/Postgres.FunctionalTests/appsettings.json
- extensions/Qdrant/Qdrant.FunctionalTests/appsettings.json
- extensions/Redis/Redis.FunctionalTests/RedisSpecificTests.cs
- extensions/Redis/Redis.FunctionalTests/appsettings.json
- extensions/Redis/Redis/RedisConfig.cs
- extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs
- extensions/SQLServer/SQLServer.FunctionalTests/appsettings.json
- service/Service/appsettings.json
- service/tests/Core.FunctionalTests/appsettings.json
- service/tests/Service.FunctionalTests/appsettings.json
- service/tests/TestHelpers/BaseFunctionalTestCase.cs
Some functional tests config used a different schema, making it harder to copy settings from service to examples to tests.
Redis config needs an update given the new tag for partition number.
Redis functional tests checking for error message were not aligned with latest code.
ElasticSearch config settings were missing in Service appsettings.json
* Add "KernelMemory" config prefix where missing.
* Update Redis config and Redis settings.
* Add ES default settings.
> Align config files schema across tests, service and examples + Config fixes

- service/Abstractions/Search/SearchClientConfig.cs
- service/Service/appsettings.json
With the exception of `MaxTokens`, properties of the [TextGenerationOptions](https://github.com/microsoft/kernel-memory/blob/dacc5047e339fe4073636b3d9b54c32438073978/service/Core/Search/SearchClient.cs#L341-L350) object used by `AskAsync` are hard-coded.
This PR addresses issues https://github.com/microsoft/kernel-memory/issues/137 and https://github.com/microsoft/kernel-memory/issues/337. It updates the [SearchClientConfig.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Search/SearchClientConfig.cs) file in the **Abstractions** project adding the properties that allows to set **Temperature**, **TopP**, **PresencePenaltiy**, etc.
Once the **Abstractions** project is updated on NuGet, the **Core** project can be in turn modified to use these new settings in …
> Add properties to set SearchClient settings like Temperature and TopP

- tools/InteractiveSetup/AppSettings.cs
- tools/InteractiveSetup/Main.cs
- tools/InteractiveSetup/UI/Answer.cs
- tools/InteractiveSetup/UI/SetupUI.cs
Speed up configuration changes and reduce chance of config errors.
When showing multiple options, read the current active one from config files, and select it as the default.
Exmaple:
> When showing multiple options, read and show the active one

- extensions/LlamaSharp/LlamaSharp.FunctionalTests/appsettings.json
- extensions/Qdrant/Qdrant.FunctionalTests/appsettings.json
- extensions/Qdrant/Qdrant.TestApplication/appsettings.json
- extensions/Qdrant/Qdrant/QdrantConfig.cs
- extensions/Qdrant/Qdrant/QdrantMemory.cs
- service/Service/appsettings.json
- service/tests/Core.FunctionalTests/appsettings.json
- service/tests/Service.FunctionalTests/appsettings.json
As described in the issue https://github.com/microsoft/kernel-memory/issues/285, it is useful to have the ability to specify the default collection used by Qdrant, so we don't need to specify it for every invocation of methos that work with index.
This PR adds a new configuration property, `DefaultIndex`, to `QdrantConfig` class. This value is used to set the default index name in the `QdrantMemory` client. If no value is provided, that the old `Constants.DefaultIndex` field is used, so backward compatibility is guaranted.
> Configure Qdrant default collection name

- extensions/AzureOpenAI/AzureOpenAITextGenerator.cs
- extensions/LlamaSharp/LlamaSharp/LlamaSharpTextGenerator.cs
- extensions/OpenAI/OpenAITextGenerator.cs
- service/Core/Search/SearchClient.cs
With the exception of `MaxTokens`, properties of the [TextGenerationOptions](https://github.com/microsoft/kernel-memory/blob/dacc5047e339fe4073636b3d9b54c32438073978/service/Core/Search/SearchClient.cs#L341-L350) object used by `AskAsync` are hard-coded.
This PR completes the work started by the PR https://github.com/microsoft/kernel-memory/pull/341. It updates [SearchClient.cs](https://github.com/microsoft/kernel-memory/blob/dacc5047e339fe4073636b3d9b54c32438073978/service/Core/Search/SearchClient.cs#L341-L350) (and the corresponding text generators) to use the new LLM request settings that are now available in the [SearchClientConfig.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Search/SearchClientConfig.cs).
> Search client update

- extensions/Qdrant/Qdrant/Client/QdrantClient.cs
Qdrant v1.8.0 has changed the response code that is returned when trying to create a collection that already exists.
Old version of Qdrant returned **400 Bad Request** when trying to create a collection that already exists. Starting from v1.8.0, this API returns **409 Conflict**. This PR addresses this breaking change (see #347).
> Bugfix for new Qdrant Create Collection API response code

- Directory.Packages.props
- extensions/AzureOpenAI/AzureOpenAI.csproj
- extensions/OpenAI/OpenAI.csproj
- service/Core/Handlers/DependencyInjection.cs
This PR solves a version mismatch between libraries. See https://github.com/microsoft/kernel-memory/issues/361.
This PR updates the package dependencies to correctly support the latest version of **Azure.AI.OpenAI library**, that is required to use the right API version of the service.
> Bump SemanticKernel dependencies to v1.6.1

- service/Abstractions/Pipeline/MimeTypes.cs
- service/Core/Handlers/TextExtractionHandler.cs
Proposal for fix #303 
Like described in the issue, the legacy Word 97-2003 files will be ignored. Also the MIME types for the XML formats are changed to reflect the actual content type for those files.
> Possible fix for 303 - Ignoring legacy Word 97-2003 files

- tools/InteractiveSetup/AppSettings.cs
- tools/InteractiveSetup/Main.cs
When you download the project in a fresh folder, running `dotnet run setup` in the service folder throws an error because development.json file does not exists.
Also if you configure using Disk storage (not for production but useful for testing) actually it uses volatile storage and does not persist anytying on disk.
it will fix #358
I've simply restored the generation of basic development file if not exists, also fixed configuration using "disk" storage type instead of "volatile"
> Fixed #358 - configuration on Disk from clean folder

- service/Core/ServiceCollectionExtensions.cs
See https://github.com/microsoft/kernel-memory/issues/393
This PR introduces two extensions method that allow to add Kernel Memory to an existing Service Collection (in a typical DI context) and automatically registers it as a singleton `IKernelMemory` service.
> Add extension methods to easily add Kernel Memory to Service Collection

- service/Core/DataFormats/Office/MsExcelDecoder.cs
Objective is to support excel files which has few blank values within the used range.
Taking example of below excel
- Currently the code ignores the blank values, and that creates distortion in the arrangement of values.
Output of the above excel file looks something like below
```
"EmployeeName", "EmployeeSalary", "EmployeeDepartment", "EmployeeCity", "EmployeeId"
"John", 1000, "Accounts", "New York", 1
"Jack", 2000, "Tax", "Bangalore", 2
"Ryan", 3000, "HR", "Tokyo", 3
"Rob", 2000, "Tax", 4
"Pablo", 5000, "Accounts", "Paris", 
```
(See the employee city for Rob has been substituted by the employee Id 4)
- With the proposed change, a default value `Blank` will be substituted when these kinds of scenarios are observed.  Consumers are free to overwrite the default value with the help of the …
> Updated MSExcelDecoder to handle blank cell values

- service/Abstractions/DataFormats/FileContent.cs
- service/Abstractions/DataFormats/IContentDecoder.cs
Decouple FileContent from MIME constants. Allow decoders to use logic to decide if a type is supported.
> Changes to new decoders interfaces/types

- service/Core/Search/SearchClient.cs
`PartitionNumber` and `SectionNumber` properties of `Citations` object are set only in the [SearchAsync](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Search/SearchClient.cs#L161-L162) method of [SearchClient](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Search/SearchClient.cs), but not in the [AskAsync](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Search/SearchClient.cs#L177) method. This PR assigns the missing properties.
> Add PartitionNumber e SectionNumber to citations

- service/Abstractions/KernelMemoryBuilderExtensions.cs
- service/Core/Search/DependencyInjection.cs
This PR adds generic overloads to the following `IKernelMemoryBuilder` extension methods, allowing to fully leverage dependency injection:
- `WithCustomIngestionQueueClientFactory`
- `WithCustomStorage`
- `WithCustomMimeTypeDetection`
- `WithCustomTextGenerator`
- `WithCustomImageOcr`
- `WithCustomPromptProvider`
- `WithCustomSearchClient`
From this list, `WithCustomEmbeddingGenerator` and `WithCustomMemoryDb` methods are missing, because providing a generic implementation of them requires a little refactoring, so it will be added later.
> Add IKernelMemoryBuilder generic oveloads

- examples/003-dotnet-Serverless/003-dotnet-Serverless.csproj
- examples/003-dotnet-Serverless/Program.cs
- extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
- extensions/Postgres/Postgres/Db/PostgresDbClient.cs
- extensions/Qdrant/Qdrant/Client/QdrantClient.cs
- extensions/Qdrant/Qdrant/QdrantMemory.cs
- service/Abstractions/MemoryStorage/IMemoryDb.cs
- service/Core/Handlers/SaveRecordsHandler.cs
- service/Core/MemoryStorage/DevTools/SimpleVectorDb.cs
I had the same problem as the submitter of this issue: https://github.com/microsoft/kernel-memory/issues/289. For every embedding during the save process, a call is made to list indexes. Using Azure AI Search, I was getting rate limit errors, i.e. `Azure.RequestFailedException with the message "You are sending too many requests. Please try again later."`
Made an adjustment to simply cache indexes that were already checked/created during the save embeddings process. This skips the unnecessary call to ListIndexes for every single embedding.
> Check index once per unique index name during save embeddings.

- extensions/AzureQueues/DependencyInjection.cs
In the following method:
https://github.com/microsoft/kernel-memory/blob/0d82c621df6150b59046fbd2b78afc97726beda0/extensions/AzureQueues/DependencyInjection.cs#L14-L21
There is a call to the `AzureQueuesConfig.Validate` method, but then the AddAzureQueuesOrchestration method is invoked, that in turns calls `AzureQueuesConfig.Validate` again:
https://github.com/microsoft/kernel-memory/blob/0d82c621df6150b59046fbd2b78afc97726beda0/extensions/AzureQueues/DependencyInjection.cs#L27
So, it is possible to safely remove the first invocation.
> Remove reduntant method calling

- extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
Now that Azure AI Search supports hybrid search (see https://github.com/microsoft/kernel-memory/pull/428), the corresponding item from the TODO list of **AzureAISearchMemory.cs** can be removed.
> Remove "support hybrid search" from TODO list

- extensions/RabbitMQ/RabbitMQPipeline.cs
- extensions/RabbitMQ/RabbitMqConfig.cs
- service/Service/appsettings.json
See https://github.com/microsoft/kernel-memory/issues/408#issuecomment-2063342815. This PR sets the `MessageId` and `Expiration` properties for RabbitMQ messages.
> Add missing properties to RabbitMQ messages

- service/Service/appsettings.json
Show how to configure logger.
Add more log settings to appsettings.json, to help with the configuration. No code changes, these are automatically picked up by .NET.
Change/Set defaults:
* "**TimestampFormat**": "[HH:mm:ss.fff] "
* "**SingleLine**": true
* "**UseUtcTimestamp**": false
* "**IncludeScopes**": false
* "**JsonWriterOptions**": { "Indented": true  }
* "**LogToStandardErrorThreshold**": "Critical"
* see https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions.logtostandarderrorthreshold
> Add more log settings to appsettings.json, change defaults

- service/Core/DataFormats/Office/MsExcelDecoder.cs
I have an excel document that has a special worksheet which is not even visible in Excel. I don't know the specifics behind this, but 
`RangeUsed()` returns null for this worksheet. This PR addresses this by skipping the worksheets for which RangeUsed() returns null.
Fix for a special kind of Excel document.
> Fix for when RangeUsed() in worksheet returns null.

- Directory.Packages.props
- KernelMemory.sln
- examples/301-discord-test-application/301-discord-test-application.csproj
- examples/301-discord-test-application/DiscordDbContext.cs
- examples/301-discord-test-application/DiscordDbMessage.cs
- examples/301-discord-test-application/DiscordMessageHandler.cs
- examples/301-discord-test-application/Program.cs
- examples/301-discord-test-application/appsettings.json
- extensions/Discord/Discord/Discord.csproj
- extensions/Discord/Discord/DiscordConnector.cs
- extensions/Discord/Discord/DiscordConnectorConfig.cs
- extensions/Discord/Discord/DiscordMessage.cs
- service/Service/appsettings.json
Allow ingesting Discord messages in memory, to populate memory and trigger AI-driven actions.
Add example, including handler and code to store Discord messages in Postgres.
* Add connector based on DiscordBod.NET to fetch messages. The Discord bot can be added to multiple servers.
* Whenever a message is received serialize the message data and trigger a memory pipeline, uploading the file to content storage.
* Pipeline steps are configurable, in order to process the serialized data with custom logic before doing anything else.
> Experimental Discord connector

- extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
- service/Core/Configuration/KernelMemoryConfig.cs
- service/Core/Handlers/SaveRecordsHandler.cs
- service/Service/appsettings.json
Add support for batch support in Azure AI Search and SaveRecordsHandler.
* New `KernelMemory:DataIngestion:MemoryDbUpsertBatchSize` setting (default: 1) to manage memory records batch size.
* Implement the new optional `IMemoryDbBatchUpsert` interface in `AzureAISearchMemory`.
* Fix old bug in `AzureAISearchMemory` occurring when `EmbeddingGenerationEnabled` is `false`.
> Azure AI Search: Add support for batching save operations

- extensions/MongoDbAtlas/MongoDbAtlas/MongoDbAtlasStorage.cs
This addresses #471. 
I just added a `contentType` to the document. Seems to fix some problems I faced with #471.
> Adding contentType to document

- clients/dotnet/WebClient/MemoryWebClient.cs
- clients/dotnet/WebClient/StringExtensions.cs
When deploying KM web service with a custom base address, the web client would still send requests to the default root of the endpoint (due to how .NET HttpClient merges BaseAddress and paths).
* Add workaround for HttpClient merge of base address + path
* Add a couple of missing await / ConfigureAwait
> Fix web client base address

- Directory.Packages.props
- extensions/AzureOpenAI/AzureOpenAIConfig.cs
- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/OpenAI/OpenAIConfig.cs
- extensions/OpenAI/OpenAITextEmbeddingGenerator.cs
- service/Service/appsettings.json
Semantic Kernel has been updated to support the `Dimensions` property for embeddings, to set the number of dimensions the resulting output embeddings should have (https://github.com/microsoft/semantic-kernel/issues/6026). This PR adds this support to Kernel Memory.
> Add support for embedding dimensions

- Directory.Packages.props
- examples/105-dotnet-serverless-llamasharp/105-dotnet-serverless-llamasharp.csproj
- examples/105-dotnet-serverless-llamasharp/Program.cs
- extensions/LlamaSharp/LlamaSharp/LlamaSharp.csproj
- service/Service/Service.csproj
LLamaSharp doesn't allow to include multiple backends at once in a packaged .NET app, requiring to build once for each backend (CPU, CUDA11, CUDA12, etc). The current code fails to "publish" due to concurring backends.
See also https://github.com/microsoft/kernel-memory/issues/498
Solve the "publish" issue by removing all LLamaSharp backends, leaving it to the end user/developer to choose one.
The need to build multiple times, once per LLamaSharp backend, persists, due to how LLamaSharp is designed. (if anyone knows of a workaround please let us know!)
> Fix dotnet publish // LLamaSharp conflicts

- KernelMemory.sln
- applications/evaluation/Evaluation.csproj
This pull request marks the beginning of our implementation of evaluation metrics for our Retrieval Augmented Generation (RAG) pipelines using the RAGAS framework.
RAGAS (RAG Assessment) is a comprehensive framework designed to evaluate RAG pipelines. RAG pipelines utilize external data to enhance the context provided to Large Language Models (LLMs). While building these pipelines is facilitated by existing tools, evaluating their performance quantitatively remains a challenge. RAGAS addresses this gap by offering tools based on cutting-edge research to evaluate LLM-generated text and provide valuable insights into the effectiveness of RAG pipelines.
The implementation will leverage Kernel Memory to deliver the following evaluation features:
- **Faithfulness**: Ensuring the generated text …
> Add evaluation root project

- extensions/SQLServer/SQLServer/SqlServerMemory.cs
Improve some areas of the SqlServer memory connector:
* avoid I/O in ctor, which could cause the service to crash with dependency injection errors. Run the initialization logic on the first call to any public method instead.
* change methods using I/O from sync to async
* use async dispose for connection, command, and data reader instances
* add missing ConfigureAwait(false) on instances async disposing logic
> SQL Server improvements to asynchronous code

- service/Core/Search/SearchClient.cs
Update SearchClient to use webPageUrl instead of static fileName for webpages
When providing webpages as facts, the "filename" currently is a static "content.url" - this provides no value when asking the LLM to include sources directly in the response (e.g. to have per paragraph sources).
When creating the facts, instead of "content.url" the webpage url is added
> Update SearchClient to use webPageUrl instead of static fileName for webpages (fixes microsoft/kernel-memory#491)

- service/Abstractions/KernelMemoryBuilderExtensions.cs
Related to https://github.com/microsoft/kernel-memory/pull/503, it allows to register an `IMemoryDb` using Dependency Injection.
> Add support for Dependency Injection with IMemoryDb

- extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs
- extensions/SQLServer/SQLServer/SqlServerMemory.cs
Resolve the issue #527 by removing size limit for tags field.
the merge command used nvarchar(256) field for tags management but it requires to remove this limit.
> Fix #527 - Use NVarchar(max) db type for tags in SQL Server

- applications/evaluation/TestSetEvaluatorBuilder.cs
- applications/evaluation/TestSetGeneratorBuilder.cs
Resolve #655 
The builders didn't have the generators or evaluators in service collection blocking the resolution of instances.
> Fix #655 - Fix DI for evaluation builders

- KernelMemory.sln
- applications/evaluation/TestSetEvaluatorBuilder.cs
- applications/evaluation/TestSetGeneratorBuilder.cs
- applications/tests/Evaluation.Tests/Evaluation.FunctionalTests.csproj
- applications/tests/Evaluation.Tests/Startup.cs
- applications/tests/Evaluation.Tests/TestsetGenerationTests.cs
- applications/tests/Evaluation.Tests/appsettings.json
> Add functional tests for the evaluation

- service/Abstractions/AI/TextGenerationOptions.cs
- service/Abstractions/Search/SearchClientConfig.cs
Currently, StopSequences initialized with Array.Empty<T>() are not deserialized correctly, resulting in an empty list even when values are provided in the configuration. 
By changing the initialization to use new List<T>(), we ensure that the StopSequences are properly deserialized from the configuration. For more details, I have created a issue: [dotnet/runtime#103282](https://github.com/dotnet/runtime/issues/103282).
> Fix reading StopSequences from the config

- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/OpenAI/OpenAITextEmbeddingGenerator.cs
In the new `GenerateEmbeddingBatchAsync` method, a debug log message is written. For coherence, this PR adds the same message also for `GenerateEmbeddingAsync`.
> Add debug logs for embedding generation

- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
I've imported about 6 million documents with PostgresDB as backend. I've created an HNSW index. When doing a search (using WebClient.Ask/Search) I keep getting timeouts. Upon further investigation, I saw that the query used in Kernel Memory is not optimisable as it's doing an inline calculation of "1 - the difference".
After I removed the "1 - " in our fork & deployed it, it was successfully using the index and I would get a response within 5 - 10 seconds.
I've used pgAdmin4 to confirm that the new query is using the index.
See also discussion with @dluc here: https://github.com/microsoft/kernel-memory/discussions/663#discussioncomment-9952593
> fix: postgres search query does not use index

- examples/110-dotnet-anthropic/Program.cs
- extensions/Anthropic/AnthropicConfig.cs
- extensions/Anthropic/AnthropicTextGeneration.cs
- extensions/Anthropic/DependencyInjection.cs
- service/Core/SemanticKernel/KernelMemoryBuilderExtensions.cs
- service/Service/ServiceConfiguration.cs
Rename class and method parameters to match the overall naming convention. See #705 and #706.
> Naming adjustments

- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
During string interpolation if dotnet culture is set to French it used comma as the decimal separator instead of period, which cased SQL error "unexpected ,"
Forcing culture-insensitive cast using `maxDistance.ToString(CultureInfo.InvariantCulture)`
> fix: maxDistance cast to string

- service/Abstractions/Constants.cs
- service/Abstractions/Context/IContext.cs
- service/Core/Handlers/TextPartitioningHandler.cs
I have a use case to prepend a header (in my case the original file path from sharepoint) in to each partition to be able to include that in the embedding and RAG. This is a minimal change with the addition of the RequestContext and leverages the existing `chunkHeader` parameter in the TextChunker.
Adds constant for `ChunkHeader` in the `Constants.CustomContext.Partitioning` class.
In `TextPartitioningHandler` we look for the existence of that context argument and default to `null` (existing behavior is null here)
> Add ChunkHeader option to request context

- Directory.Packages.props
- extensions/OpenAI/OpenAI.UnitTests/GPTTokenizersTests.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT2Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT3Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT4Tokenizer.cs
Microsoft ML Tokenizer library is still in beta and undergone lots of modifications, so it is better to always use the latest version. Also in my project where I 'm using Microsoft.ML.Tokenizer I'm actually using some of the feature of the latest beta, and this prevents me to using newest version of Kernel Memory tue to errors.
Simply updated the reference, then updated a couple of classes and wrote a unit test to verify I didn't break anything.
> Updated microsoft ML tokenizer to latest beta.

- extensions/OpenAI/OpenAI/Tokenizers/GPT2Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT4Tokenizer.cs
- extensions/OpenAI/OpenAI/Tokenizers/GPT4oTokenizer.cs
- service/Service/ServiceConfiguration.cs
* Add new tokenizer for GPT-4o and 4o mini
* Fix service bootstrap warnings caused by unselected tokenizer. Default to GPT4 tokenizer.
> New tokenizer for gpt4o. Fix warnings.

- service/Service/Program.cs
Fix: the new health probe endpoint should be added only when the web service is enabled.
> Add health probe only when web service is running

- extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs
- extensions/SQLServer/SQLServer.FunctionalTests/appsettings.json
- extensions/SQLServer/SQLServer/DependencyInjection.cs
- extensions/SQLServer/SQLServer/SqlServerMemory.cs
- service/tests/Core.FunctionalTests/DefaultTestCases/RecordDeletionTest.cs
- service/tests/TestHelpers/BaseFunctionalTestCase.cs
* Add a new functional test, currently used only for MSSQL, to test memory record deletion. See #712 
* Refactor MSSQL .NET object disposal to be more explicit
> Add functional test for MSSQL

- extensions/Postgres/Postgres.FunctionalTests/ConcurrencyTests.cs
- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
- extensions/Postgres/Postgres/PostgresMemory.cs
See https://github.com/microsoft/kernel-memory/issues/679.
If I call `ImportDocumentAsync` and then `AskAsync`, after the execution I see that two sessions are still in the list:
This PR adds the disposal the **NpgsqlDataSource** after each connection. In this way, no pending sessions remain when the execution completes.
~~NOTE: for the moment, I have left the `IDisposable` interface on **PostgresDbClient.cs** (with an empty implementation for reference), but actually it is no longer necessary, as explained in https://github.com/microsoft/kernel-memory/issues/679#issuecomment-2202303865. So, I think it could be safely removed.~~
> Add disposal of NpgsqlDataSource after opening connection

- applications/evaluation/Evaluators/AnswerCorrectness/AnswerCorrectnessEvaluator.cs
- applications/evaluation/Evaluators/AnswerCorrectness/StatementExtraction.cs
- applications/evaluation/Evaluators/ContextRecall/ContextRecallEvaluator.cs
- applications/evaluation/Evaluators/ContextRecall/GroundTruthClassifications.cs
- applications/evaluation/Evaluators/ContextRelevancy/ContextRelevancyEvaluator.cs
- applications/evaluation/Evaluators/Faithfulness/FaithfulnessEvaluations.cs
- applications/evaluation/Evaluators/Faithfulness/FaithfulnessEvaluator.cs
- applications/evaluation/Evaluators/Relevance/RelevanceEvaluator.cs
- applications/evaluation/Prompts/Evaluation/ContextPrecision.txt
- applications/evaluation/Prompts/Evaluation/ContextRecall.txt
- applications/evaluation/Prompts/Evaluation/Correctness.txt
- applications/evaluation/Prompts/Evaluation/Faithfulness.txt
- applications/evaluation/Prompts/Extraction/Keyphrase.txt
- applications/evaluation/Prompts/Extraction/Question.txt
- applications/evaluation/Prompts/Extraction/Statements.txt
- applications/evaluation/Prompts/SyntheticData/ConditionalQuestion.txt
- applications/evaluation/Prompts/SyntheticData/MultiContextQuestion.txt
- applications/evaluation/Prompts/SyntheticData/QuestionAnswer.txt
- applications/evaluation/Prompts/SyntheticData/ReasoningQuestion.txt
- applications/evaluation/TestSetGenerator.cs
- applications/tests/Evaluation.Tests/Evaluation.FunctionalTests.csproj
Use json_obect output format from LLM in the Testset generation and Evaluation
Add POCO objects generated by LLM and update the deserialization.
> Fix evaluations and test set generation to use json_object output format from LLMs

- examples/002-dotnet-Serverless/Utils.cs
- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/AzureOpenAI/AzureOpenAITextGenerator.cs
- extensions/AzureOpenAI/Internals/AzureOpenAIClientBuilder.cs
- extensions/AzureOpenAI/Internals/ClientSequentialRetryPolicy.cs
- extensions/OpenAI/OpenAI/Internals/.editorconfig
- extensions/OpenAI/OpenAI/Internals/ChangeEndpointPolicy.cs
- extensions/OpenAI/OpenAI/Internals/ClientSequentialRetryPolicy.cs
- extensions/OpenAI/OpenAI/Internals/OpenAIClientBuilder.cs
- extensions/OpenAI/OpenAI/Internals/SkClientBuilder.cs
- extensions/OpenAI/OpenAI/OpenAITextEmbeddingGenerator.cs
- extensions/OpenAI/OpenAI/OpenAITextGenerator.cs
When sending too many requests to Azure / OpenAI and receiving status code 429, the response includes how long to wait before retrying. The same might be true for status code 503.
KM default retry strategy ignores this information, often retrying too soon, and causing unnecessary errors and potential pipeline failures.
Fix the retry policy to honor these headers in case of 429 and 503:
* retry-after-ms
* x-ms-retry-after-ms
* Retry-After
> Honor retry delay on Azure/OpenAI status codes 429 and 503

- service/Core/SemanticKernel/SemanticKernelTextEmbeddingGenerator.cs
- service/Core/SemanticKernel/SemanticKernelTextGenerator.cs
Currently it's possible to inject Semantic Kernel classes into KM only using 
- IKernelMemoryBuilder.WithSemanticKernelTextGenerationService
- IKernelMemoryBuilder.WithSemanticKernelTextEmbeddingGenerationService
- IServiceCollection.AddSingleton<ITextGenerator>(instance)
- IServiceCollection.AddSingleton<ITextEmbeddingGenerator>(instance)
However, it's not possible to create an instance of Semantic Kernel classes directly without writing a custom wrapper class first. Since the project already includes such wrapper, as internal classes, this PR changes them to public classes, to reduce the amount of code to write.
Classes:
- SemanticKernelTextGenerator
- SemanticKernelTextEmbeddingGenerator
> Make SK text and embedding generator wrappers public

- .github/workflows/docker-amd64.yml
- .github/workflows/docker-armd64.yml
- Dockerfile
- tools/dockerize-amd64.sh
- tools/dockerize-arm64.sh
* Remove multi-arch builds, which are not working correctly on ARM (segmentation fault)
* Split github workflow by arch. ARM arch dockerization to be run manually for now, until fixed.
* Deprecate "sha" labels to avoid confusion)
> Fixing dockerization for ARM64

- Directory.Packages.props
- extensions/Postgres/Postgres.FunctionalTests/ConcurrencyTests.cs
- extensions/Postgres/Postgres/Internals/PostgresDbClient.cs
- extensions/Postgres/Postgres/Postgres.csproj
- extensions/Postgres/Postgres/PostgresMemory.cs
See https://github.com/microsoft/kernel-memory/issues/789, in particular https://github.com/microsoft/kernel-memory/issues/789#issuecomment-2391108832.
This PR restores the old Postgres connection handling, following the suggestion reported at https://github.com/npgsql/npgsql/issues/5862#issuecomment-2391068719.
If, for some reason, the default connection pooling behavior causes issues like https://github.com/microsoft/kernel-memory/issues/679, the recommend solution is to add the `Pooling=false` setting in the connection string.
> Revert Postgres connection handling

- extensions/RabbitMQ/RabbitMQ.TestApplication/Program.cs
- extensions/RabbitMQ/RabbitMQ.TestApplication/appsettings.json
- extensions/RabbitMQ/RabbitMQ/RabbitMQConfig.cs
- extensions/RabbitMQ/RabbitMQ/RabbitMQPipeline.cs
- service/Service/appsettings.json
Allow to configure the RabbitMQ pipeline threads usage and the delay between failures.
Add "KernelMemory" application name to RabbitMQ logs.
New configuration settings:
* ConcurrentThreads: how many threads to use for each queue to process messages.
* PrefetchCount: how many messages to prefetch from each queue. The value is recommended to be greater than ConcurrentThreads.
* DelayBeforeRetryingMsecs: how long to wait before retrying to process a message that failed. The delay is applied in the client code, not using delayed exchanges.
> RabbitMQ pipeline improvements

- service/Abstractions/Pipeline/MimeTypes.cs
TryGetFileType allows to check file type support before using ImportDocumentAsync, enabling a fallback to ImportTextAsync without relying on try-catch blocks.
> Add TryGetFileType method to MimeTypesDetection

- examples/210-KM-without-builder/Program.cs
- examples/212-dotnet-ollama/Program.cs
- extensions/Anthropic/AnthropicTextGeneration.cs
- extensions/AzureOpenAI/AzureOpenAITextEmbeddingGenerator.cs
- extensions/AzureOpenAI/AzureOpenAITextGenerator.cs
- extensions/ONNX/Onnx/OnnxTextGenerator.cs
- extensions/Ollama/Ollama/DependencyInjection.cs
- extensions/Ollama/Ollama/OllamaTextEmbeddingGenerator.cs
- extensions/Ollama/Ollama/OllamaTextGenerator.cs
- extensions/OpenAI/OpenAI/OpenAITextEmbeddingGenerator.cs
- extensions/OpenAI/OpenAI/OpenAITextGenerator.cs
- service/Abstractions/Constants.cs
- service/Abstractions/Context/IContext.cs
- service/Abstractions/Context/IContextProvider.cs
- service/Core/MemoryServerless.cs
Allow to override the model name during a request, using request context arguments.
The feature is available only for Anthropic and Ollama. Updated example 212 showing how to override Ollama settings at runtime.
The feature is not supported when using OpenAI/Azure OpenAI, because the underlying connectors hard code the model name in client instances and would require a considerable amount of refactoring, plus memory overhead, to support this feature. See https://github.com/microsoft/semantic-kernel/issues/9337
> Support Request Context in Ollama and Anthropic generators

- service/tests/Abstractions.UnitTests/Diagnostics/SensitiveDataLoggerTests.cs
Contributing unit tests for the `SensitiveDataLogger` to cover a recently fixed bug and prevent future regression.
N/A - unit tests only
> Unit tests for the SensitiveDataLogger

- service/Abstractions/Constants.cs
- service/Abstractions/Context/IContext.cs
- service/Core/Search/SearchClient.cs
Need the ability to control the MaxMatchesCount per Ask request instead of always defaulting to the configuration value.
Add  MaxMatchesCount constant and extensions.
> Add ability to control MaxMatchesCount for Ask via IContext

- service/Core/Configuration/ServiceConfig.cs
- service/Service.AspNetCore/WebAPIEndpoints.cs
- service/Service.AspNetCore/WebApplicationBuilderExtensions.cs
- service/Service/Program.cs
- service/Service/appsettings.json
We have some important documents that need to be imported to Kermel Memory that are larger than the current ASP.NET Core default maximum request body size limit of 30 MB (~28.6 MiB).
https://github.com/aspnet/Announcements/issues/267
It is not currently possible to set the `MaxRequestBodySize` from configuration making it impossible to override this limit when running Kernel Memory from the Docker container image.
https://github.com/dotnet/aspnetcore/issues/4765
This PR adds a new `MaxUploadRequestBodySize` property to the `ServiceConfig` class that defaults to `null`. 
- When the setting is `null` the default ASP.NET Core `MaxRequestBodySize` continues to be applied as is currently the case
- When a value is provided it will be configured on the upload endpoint using the …
> Support configuring the MaxRequestBodySize for the upload endpoint

- service/Abstractions/Models/DataPipelineStatus.cs
- service/Abstractions/Pipeline/DataPipeline.cs
Removed the `Failed` property from `DataPipelineStatus` and reordered the `Empty` property with `JsonPropertyOrder` of 1. Updated `DataPipeline` class: refactored `Log` method to use null-coalescing assignment and adjusted `ToDataPipelineStatus` method to reflect the removal of the `Failed` property.
See https://github.com/microsoft/kernel-memory/discussions/709
> Refactor DataPipelineStatus and DataPipeline classes

- applications/tests/Evaluation.Tests/appsettings.json
- examples/001-dotnet-WebClient/file9-settings.json
- examples/002-dotnet-Serverless/appsettings.json
- examples/002-dotnet-Serverless/file9-settings.json
- examples/105-dotnet-serverless-llamasharp/appsettings.json
- examples/210-KM-without-builder/appsettings.json
- examples/401-evaluation/appsettings.json
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/LlamaSharpTextEmbeddingGeneratorTest.cs
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/LlamaSharpTextGeneratorTest.cs
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/LlamaSharpTokenizerTest.cs
- extensions/LlamaSharp/LlamaSharp.FunctionalTests/appsettings.json
- extensions/LlamaSharp/LlamaSharp/DependencyInjection.cs
- extensions/LlamaSharp/LlamaSharp/LlamaSharpConfig.cs
- extensions/LlamaSharp/LlamaSharp/LlamaSharpModelConfig.cs
- extensions/LlamaSharp/LlamaSharp/LlamaSharpTextEmbeddingGenerator.cs
- service/Service/ServiceConfiguration.cs
- service/Service/appsettings.json
- service/tests/Core.FunctionalTests/appsettings.json
- service/tests/Service.FunctionalTests/appsettings.json
Allow to generate embeddings using local models in GGUF format.
> Add LlamaSharp embeddings generator

- extensions/SQLServer/SQLServer/SqlServerMemory.cs
A simple bugfix for SQLServerMemory. The semaphore wasn't released when "is ready" changes from "false" to "true" while the code was waiting for the semaphore. Meaning if specifically 3 or more tasks run into that code at the same time, the third task as well as all others are gonna be stuck in a deadlock waiting for the semaphore. This only happens during the first initialization, since subsequent calls will leave before waiting for the semaphore.
> Bugfix SQLServerMemory semaphore not released properly

- .dockerignore
When building the container image locally after building the Visual Studio solution, a total of 3.62 GB of data is transferred in the Docker build context, slowing down the container build duration.
Fix a mistake in the `.dockerignore` file that results in the `bin` and `obj` folders being included in the build context.
Ignore the `docs`, `examples`, and `infra` folders as these are not required to build the service project.
Results in the build context being reduced to 7.6 MB.
> Reduce Docker build context by fixing errors in .dockerignore

- service/Core/Handlers/TextPartitioningHandler.cs
See https://github.com/microsoft/kernel-memory/discussions/886#discussioncomment-11229562
Updated the condition to check if `partitionContent` is empty by using the `IsEmpty` property instead of converting it to a byte array and checking its length. This change improves efficiency and readability.
> Optimize empty check for BinaryData

- service/Core/Configuration/ServiceConfig.cs
- service/Service.AspNetCore/WebAPIEndpoints.cs
- service/Service/appsettings.json
Fix typo in max HTTP upload size logic used by the web service.
Change range, allowing to set the max HTTP upload size to 1Mb.
> KM web service: fix max upload size logic

- service/Core/Handlers/GenerateEmbeddingsHandlerBase.cs
Notes added inline for future reference and development of the embedding cache feature.
> Rename embedding cache files

- examples/001-dotnet-WebClient/Program.cs
- examples/002-dotnet-Serverless/Program.cs
- service/Core/Pipeline/Queue/DevTools/SimpleQueues.cs
- service/Service.AspNetCore/WebAPIEndpoints.cs
- service/Service/Program.cs
Add name, description and summary to KM web service OpenAPI manifest.
> Improve KM webservice OpenAPI details

- extensions/SQLServer/SQLServer/SqlServerMemory.cs
- service/Core/Pipeline/Queue/DevTools/SimpleQueues.cs
Under some circumstances, SemaphoreSlim.WaitAsync() can fail, e.g. throwing an OperationCanceledException. In these cases, the internal semaphore counter didn't change, so SemaphoreSlim.Release() should not be called, to avoid exceptions.
Classes affected:
- SqlServerMemory (initialization)
- SimpleQueue (message dispatching)
> Fix SemaphoreSlim release logic

- examples/002-dotnet-Serverless/Program.cs
- service/Abstractions/Constants.cs
- service/Abstractions/Context/IContext.cs
- service/Abstractions/Search/SearchClientConfig.cs
- service/Core/Search/SearchClient.cs
- service/Core/Search/SearchClientResult.cs
- service/Service/appsettings.json
When importing chat messages or running tests with small files or without IDs, the storage might fill up with duplicate chunks of text that affect the number of tokens used when generating an answer.
When using the ASK API, after fetching N records from storage, discard duplicates and use only unique chunks in the RAG prompt.
The behavior is configurable via `SearchClientConfig.IncludeDuplicateFacts` and request context `custom_rag_include_duplicate_facts_bool` arg.
> RAG: discard duplicate facts by default

- clients/dotnet/WebClient/MemoryWebClient.cs
- extensions/AzureQueues/AzureQueuesPipeline.cs
- Changed from PostAsync to SendAsync for correct request handling.
- Adjusted HttpCompletionOption for proper streaming behavior.
Resolves issue with previous streaming setup.
Changed from PostAsync to SendAsync for correct request handling and added the HttpCompletionOption so the operation completes as soon as the initial headers are sent.
> fix: Resolve streaming bug in MemoryWebClient

- extensions/AWS/S3/AWSS3Config.cs
- extensions/AWS/S3/AWSS3Storage.cs
- service/Service/appsettings.json
Allow the use of [instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) for authentication and the proper use of [credential chain](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html).
Added AWS S3 Extension CredentialChain authentication method to use default credentials
> Update AWS S3 Extension to allow for use of credential chain.

- examples/301-discord-test-application/301-discord-test-application.csproj
- examples/301-discord-test-application/DiscordDbContext.cs
- examples/301-discord-test-application/DiscordMessageHandler.cs
- examples/301-discord-test-application/Program.cs
- service/Abstractions/KernelMemoryBuilderBuildOptions.cs
- service/Service.AspNetCore/WebApplicationBuilderExtensions.cs
- service/tests/Core.UnitTests/KernelMemoryBuilderTest.cs
* Update packages
* Fix postgres dependency injection
* Update WebApplicationBuilderExtensions extension
> Update discord example

- applications/evaluation/Evaluators/Faithfulness/FaithfulnessEvaluator.cs
- applications/evaluation/Evaluators/Relevance/RelevanceEvaluator.cs
- extensions/Chunkers/Chunkers/MarkDownChunker.cs
- extensions/Chunkers/Chunkers/PlainTextChunker.cs
- extensions/Postgres/Postgres/PostgresMemory.cs
- service/Abstractions/HTTP/SSE.cs
- service/Abstractions/Models/MemoryAnswer.cs
- service/Abstractions/Text/StringBuilderExtensions.cs
- service/Abstractions/Text/StringExtensions.cs
- service/Core/DataFormats/Image/ImageDecoder.cs
- service/Core/DataFormats/Office/MsExcelDecoder.cs
- service/Core/DataFormats/Office/MsPowerPointDecoder.cs
- service/Core/DataFormats/Office/MsWordDecoder.cs
- service/Core/DataFormats/Pdf/PdfDecoder.cs
- service/Core/DataFormats/WebPages/HtmlDecoder.cs
- service/Core/Handlers/SummarizationHandler.cs
- service/Core/Handlers/SummarizationParallelHandler.cs
- service/Core/Handlers/TextExtractionHandler.cs
- service/tests/Abstractions.UnitTests/Text/StringExtensionsTest.cs
Make text more consistent across Unix and Windows environments, avoiding the `\r` character in favor of the Unix new line ending.
See https://github.com/microsoft/kernel-memory/issues/975
> Normalize text new line to Unix-style

- Dockerfile
SQL Server memory cannot be configured when using the Docker image because it depends on ICU which is not installed in the `dotnet/aspnet:alpine` image. This results in a `System.NotSupportedException` being thrown at runtime when `SqlConnection` attempts to open a connection.
```
System.NotSupportedException: Globalization Invariant Mode is not supported.
at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
```
Update the `Dockerfile` to install `icu-libs` and set the `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` environment variable as outlined in the [Enabling (or disabling) globalization …
> Install ICU in Docker image to support SQL Server memory

- extensions/AWS/S3/AWSS3Config.cs
- extensions/AWS/S3/AWSS3Storage.cs
This PR adds support for `ForcePathStyle` configuration in `AWSS3Config`
- Added a `ForcePathStyle` boolean property to `AWSS3Config` (default: `false`)
- Updated `AWSS3Storage` to pass the value to the `AmazonS3Config.ForcePathStyle` property
- Maintains backward compatibility with AWS S3 by leaving the default behavior unchanged
- Improves compatibility with services like MinIO, LocalStack, and others that require path-style requests
This change is fully backward compatible and has no effect on current configurations unless explicitly enabled.
> Add ForcePathStyle support to AWSS3Config for MinIO compatibility

- service/Service.AspNetCore/WebAPIEndpoints.cs
- swagger.json
- tools/km-cli/upload-file.sh
OpenAPI specs incorrectly mapping "tags" to an object, and missing the "explode" encoding for "steps" and "tags". This was also making Swagger UI unusable for the upload endpoint.
Fix specs, swagger.json in the root file, and update the same bash script under /tools/
> Fix upload OpenAPI specs of “tags” and “steps” fields
